osbuild/cockpit-composer

components/Modal/CreateRecipe.js, data/MetadataApi.js, data/RecipeApi.js, pages/recipe/index.js, pages/recipeEdit/index.js, pages/recipes/index.js
These updates include the ability to click Create Recipe on recipes page, specify a recipe name and submit the form.
After clicking Save or pressing Enter in the Create Recipe dialog, the Edit Recipe page will display with the new recipe name.
=> Including ability to create a new recipe

.github/ISSUE_TEMPLATE.md
When creating a new issue this template will be loaded automatically in the text editor. 
I can add a similar one for pull requests, just let me know what items the team considers important to be outlined in a PR description.
=> Add issues template to help us report bugs better

data/RecipeApi.js, pages/recipeEdit/index.js
The following updates are included in this PR:
- When I remove a component, then the component is removed from the list of Selected Components.
- *NOTE:* this does not include removing dependencies that were included in the recipe as a result of adding the component
- Given that a component is removed, when I save the recipe and reload the recipe contents, then I do not see the component listed.
- Given that a filtered list of inputs displays, when I add a component, then the list is updated to not show the (+) Add icon for the added component. And when the filter is cleared, the list of inputs also correctly shows/hides the (+) icon based on whether the component is in the recipe or not.
- When I filter the list of inputs, the list of inputs correctly shows/hides the (+) icon based on …
=> Save recipe

README.md
I have removed the section about bootstrapping a new project from scratch b/c it doesn't belong here.
=> Minor README updated. Relates to #39

components/Actions/Actions.js, components/CardView/CardView.js, components/EmptyState/EmptyState.js, components/Layout/Header.js, components/Layout/Layout.js, components/Layout/Navigation.js, components/Layout/PfBreakpoints.js, components/Layout/PfVerticalNavigation.js, components/Link/Link.js, components/ListView/AppListView.js, components/ListView/ComponentDetailsView.js, components/ListView/ComponentInputs.js, components/ListView/ComponentSummaryList.js, components/ListView/ComponentTypeIcons.js, components/ListView/DependencyListView.js, components/ListView/ListItemExpand.js, components/ListView/ListItemExpandRevisions.js, components/ListView/ListItemLabel.js, components/ListView/ListViewExpand.js, components/ListView/ProjectListView.js, components/ListView/RecipeContents.js, components/ListView/RecipeListView.js, components/ListView/listview-expand.js, components/Modal/CreateComposition.js, components/Modal/CreateRecipe.js, components/Toolbar/Toolbar.js, components/Wizard/Wizard.js, components/Wizard/WizardView.js, package.json
These are mostly spaces, indentations, long lines and unused imports fixes. I've used `eslint --fix` and then followed the rest by hand.  All changes are for things under `components/`. 
This PR drops the eslint errors and warnings count by 50% to around 1200.
=> Multiple eslint fixes

core/constants.js, entrypoint.sh, pages/apps/index.js, pages/environments/index.js, pages/home/index.js, pages/recipe/index.js, pages/recipes/index.js, pages/stages/index.js, pages/users/index.js, public/js/config.js, webpack.config.js
Touched pretty much all files except `pages/recipeEdit/index.js` to avoid introducing conflicts for @jgiardino
=> More eslint fixes for pages/

components/ListView/ComponentDetailsView.js, components/ListView/ComponentSummaryList.js, core/constants.js, data/MetadataApi.js, data/RecipeApi.js, pages/recipeEdit/index.js
See https://github.com/weldr/bdcs-api-rs/pull/43 for the matching API changes.
=> UI changes needed for API changes

components/EmptyState/EmptyState.js, components/ListView/ListItemCompositions.js, components/ListView/ListItemExpandRevisions.js, package.json, pages/recipe/index.js
This PR includes UI mockup for how compositions would be listed on the Compositions tab when viewing a recipe.
For consistency, I also made updates to the Revisions tab so that compositions are labeled the same.
Additionally, the revisions .js file was updated to fix linting issues.
=> Compositions

components/Layout/Layout.js, components/ListView/RecipeListView.js, components/Modal/CreateComposition.js, components/Notifications/Notification.js, data/NotificationsAPI.js, data/RecipeApi.js, pages/recipe/index.js, pages/recipeEdit/index.js, pages/recipes/index.js
The PR provides updates for the following:
- https://trello.com/c/RV66gJft/227-3-ui-toast-notifications
- https://trello.com/c/QDUGy1OX/165-3-ui-create-composition
=> Notifications and Create Composition

components/Modal/CreateComposition.js
removed arch option i686
Changed button label OK to Create
=> Create Composition dialog updates

components/Notifications/Notification.js, data/NotificationsApi.js, data/RecipeApi.js, pages/recipeEdit/index.js
Includes updates for:
* https://trello.com/c/jpScBhhz/228-5-ui-update-save-to-use-updated-api
* https://trello.com/c/gZVZ2XEN/212-3-rfe-add-notifications-when-recipe-is-saved
Save was updated to include version number so that
version is automatically incremented, then recipe details
are reloaded to display new version number. Version number
is now visible in the Edit Recipe header.
Notifications were updated to include messages for save;
messages were also refactored; close function was updated
to accept either a message index or message label; notifications
component was also updated to support all message types (e.g.
warning, error, info).
=> Save updates - include version; include notification

data/RecipeApi.js
This fixes a bug related to removing components. 
Steps to reproduce:
1. Find a recipe where recipe.modules length > 0
2. Remove one of the components that is listed in recipe.modules
3. Save the recipe then refresh the page
4. Result => the component is still listed in the recipe
On save, the components that are saved with the recipe are the ones in recipe.modules and recipe.packages. If the component that's removed is originally from recipe.modules, but isn't removed from recipe.modules, then the result of remove and save will not actually remove the component.
To fix this, the components listed in recipe.packages are identified as "RPM" and components listed in recipe.modules are identified as "Module". This way, recipe.packages and recipe.modules can be correctly updated when …
=> fixing bug with removing components

pages/home/index.js
For the usability test, includes contents on the Overview/home page about the product and provides definitions for terminology that will display.
=> adding contents to Overview page

.travis.yml, Makefile, README.md
@henrywang @bcl @wgwoods please review. Currently blocked by https://github.com/weldr/welder-deployment/pull/9
=> Run end-to-end tests in Travis CI with CentOS 7 metadata

test/end-to-end/pages/editRecipe.js, test/end-to-end/pages/toastNotif.js, test/end-to-end/test/test_editRecipe.js
Acceptance criteria: When I click the Save button after some
changes on a recipe I should be able to see a notification
which tells me that the recipe was saved.
=> Add recipe save notification case.

test/end-to-end/config.json, test/end-to-end/test/test_editRecipe.js
Add two wait steps in Save Recipe Test to improve case running stability.
=> Remove kickstart composition type and add more types due to UI change.

.travis.yml, Makefile, components/Actions/Actions.js, components/CardView/CardView.js, components/Layout/Header.js, components/Layout/PfVerticalNavigation.js, components/ListView/ComponentDetailsView.js, components/ListView/ComponentInputs.js, components/ListView/ListItemCompositions.js, components/ListView/ListItemExpandRevisions.js, components/Modal/CreateRecipe.js, components/Wizard/Wizard.js, components/Wizard/WizardView.js, core/history.js, core/router.js, core/utils.js, data/MetadataApi.js, data/RecipeApi.js, package.json, pages/home/index.js, pages/recipe/index.js, pages/recipeEdit/index.js, pages/recipes/index.js, run.js, webpack.config.js
Two fixes:
1. Fix eslint running error.
2. Fix some of eslint errors. There's still some eslint errors in code. I need to discuss with @jgiardino and @bcl.
=> Fix eslint running error and some of eslint error of javascript style.

components/Layout/Layout.js, pages/common.css, pages/variables.css
Fix for the eslint errors from https://github.com/weldr/welder-web/pull/90. 
@henrywang if you want you can cherry-pick this commit inside your own pull request and then close this one.
=> Fix a few remaining stylelint errors

test/end-to-end/.eslintrc
=> Ignore missing nightmare imports in e2e tests

data/MetadataApi.js, data/RecipeApi.js, pages/recipeEdit/index.js, pages/recipes/index.js
1. Fix ui_type bug. ui_type is a key of object, cannot be changed to uiType.
2. Fix for of bug.
3. Fix a Promise bug.
4. Fix user_selected bug. All of component property will be user_selected.
=> Fix some bugs.

components/Layout/Layout.js, components/Layout/PfVerticalNavigation.js, core/utils.js
=> Fix several eslint errors

test/end-to-end/README.md, test/end-to-end/test/test_createRecipe.js, test/end-to-end/test/test_editRecipe.js, test/end-to-end/test/test_recipes.js, test/end-to-end/test/test_viewRecipe.js
Update README.md to support case ID and test type.
Add a new npm running script in package.json to support run Acceptance
test only.
Update "Save Recipe Test" to fix failed issue in Travis only.
=> Add test case ID in each case and test type in each group cases.

.gitignore, run.js
This will contain a JSON object with "build-version" set to the git
tag and hash, or to UNKNOWN if git fails.
=> Create ./core/build-version.json with the git build version

components/Actions/Actions.js, components/CardView/CardView.js, components/EmptyState/EmptyState.js, components/Layout/Layout.js, components/Link/Link.js, components/ListView/ComponentDetailsView.js, components/ListView/ComponentInputs.js, components/ListView/ComponentSummaryList.js, components/ListView/ComponentTypeIcons.js, components/ListView/DependencyListView.js, components/ListView/ListItemComponents.js, components/ListView/ListItemCompositions.js, components/ListView/ListItemExpandRevisions.js, components/ListView/ListItemLabel.js, components/ListView/ListView.js, components/ListView/RecipeContents.js, components/ListView/RecipeListView.js, components/Modal/CreateComposition.js, components/Modal/ExportRecipe.js, components/Notifications/Notification.js, components/Pagination/Pagination.js, components/Toolbar/Toolbar.js, components/Wizard/WizardView.js, pages/error/index.js, pages/recipe/index.js, pages/recipeEdit/index.js, test/end-to-end/.eslintrc
1. Fix prop type issue on edit recipe page.
2. Update end-to-end eslint setting to have the same max-len (130).
3. Fix accessing PropTypes via the main React package deprecated issue.
=> Fix issues.

test/end-to-end/config.json, test/end-to-end/pages/editRecipe.js, test/end-to-end/pages/exportRecipe.js, test/end-to-end/pages/recipes.js, test/end-to-end/pages/viewRecipe.js, test/end-to-end/test/test_editRecipe.js, test/end-to-end/test/test_recipes.js, test/end-to-end/test/test_viewRecipe.js, test/end-to-end/utils/apiCall.js
1. add case to test recipe export on recipes, view recipe, and edit recipe page.
=> Add recipe export test case.

test/end-to-end/config.json, test/end-to-end/test/test_editRecipe.js, test/end-to-end/test/test_recipes.js, test/end-to-end/test/test_viewRecipe.js
I have taken the existing composition test and looped it over all 5 composition types by placing the test within a forEach loop. I also re-factored the config so that "composition" is now an array of objects. Thanks for any feedback you can offer.
=> Updated Composition tests to run for all types, not just ostree.

components/Modal/ExportRecipe.js, components/Modal/PendingChanges.js, components/Toolbar/Toolbar.js, core/utils.js, pages/recipeEdit/index.js
Updated state for modals. Added new modal for pending changes in edit recipe. Fixed api port when run through cockpit.
=> Modal updates and fixed cockpit integration.

test/end-to-end/package.json, test/end-to-end/pages/createRecipe.js, test/end-to-end/test/test_createRecipe.js
1. Fix eslint eslint-config-airbnb version compatibility issue.
2. Update Create Recipe case to check Help-Block message.
3. Add Create Recipe case to support Enter key instead of Save button.
4. Add Create Recipe case to verify alert message when changing input focus.
=> Fix issue and add new case

README.md, package.json, test/unit/create.composition.spec.js, test/unit/env.js, test/unit/home.index.spec.js
1. Add unit test case for CreateComposition.js
2. Update Jest to 20.x.x to support toHaveLength and more mock features
3. Remove sinon because Jest has full mock support now
=> Add new unit test case and some improvements.

Makefile, test/end-to-end/package.json
Check out welder-web code not from master but from local which is checked out by Travis based on PR.
=> Fix welder-web container repo issue.

test/end-to-end/pages/editRecipe.js, test/end-to-end/pages/viewRecipe.js
Please DO NOT merge this PR before PR#118 gets merged.
=> Update page object due to new Edit Recipe page layout.

Dockerfile, test/end-to-end/Dockerfile
Related to https://github.com/weldr/welder-deployment/pull/12
=> Update names of base docker images

test/end-to-end/pages/editRecipe.js, test/end-to-end/pages/viewRecipe.js, test/end-to-end/test/test_editRecipe.js, test/end-to-end/test/test_recipes.js, test/end-to-end/test/test_viewRecipe.js
Add a wait action in copy and paste case to improve stability.
=> Update CSS selector according to PR#123 and case stability improvement.

Makefile
this makes for less cluttered logs
=> Make wget progress less verbose

Makefile, README.md, welder-web.spec
Added the ability to easily make an rpm/srpm that will install into cockpit.
=> Cockpit Integration and make rpm functionality

.travis.yml
1. Fix coverage issue.
2. Resolve one case stability issue.
=> Fix coverage issue.

pages/recipes/index.js, test/unit/index.norecipes.spec.js
Update Empty State message and include Create Recipe action
to be more consistent with the patternfly pattern. Remove actions
from the toolbar kebab that are not functional and have no plans
to be implemented in the near future.
=> Update Recipes page empty state and non-functional actions

test/end-to-end/pages/viewRecipe.js
Add header class before ol class to make finding element with element hierarchy.
=> Update wait element to make case more stable.

Makefile, README.md, test/end-to-end/README.md, test/end-to-end/config.json, test/end-to-end/package.json, test/end-to-end/test/test_importSanity.js, test/end-to-end/utils/apiCall.js
No database query any more, use API call instead.
=> Remove metadata.db depencence for test test_importSanity.

Dockerfile.buildrpm, Makefile, core/utils.js
This PR takes the fixes from #187 that unbreak CI, and also adds some important debug logging.
I think these three are all simple and straightforward, and should land ASAP to unblock other work.
@atodorov, @jgiardino , can you please land this quickly?
=> Fix package build and CI (urgent)

.travis.yml
According to @martinpitt suggestion, add Travis CI to automatically rebase PRs on top of master before test running.
=> Travis CI automatically rebases PRs on top of master.

test/end-to-end/config.json, test/end-to-end/test/test_editRecipe.js, test/end-to-end/test/test_recipes.js, test/end-to-end/test/test_viewRecipe.js
1. Remove package version in config.json.
2. Update package to httpd.
3. Add empty component checking to find issue when depsolve not working.
=> Update end to end test config and export related cases according to PR#185.

test/end-to-end/config.json, test/end-to-end/package.json, test/end-to-end/pages/viewBlueprint.js, test/end-to-end/test/test_viewBlueprint.js
1. should show correct blueprint description title
2. should show correct blueprint name under Details tab
3. should show correct blueprint description under Details tab
4. should update description
5. should not update description if click cancel button
=> Add 5 cases on view blueprint page.

Dockerfile, Dockerfile.buildrpm, Dockerfile.cockpit, Dockerfile.metadata, Dockerfile.nodejs, Dockerfile.with-coverage, test/end-to-end/Dockerfile
MAINTAINER is deprecated now. As doc suggested, use LABEL instead.
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
=> Replace MAINTAINER with LABEL instruction in Dockerfile.

test/end-to-end/config.json, test/end-to-end/pages/blueprints.js, test/end-to-end/pages/deleteBlueprint.js, test/end-to-end/test/test_blueprints.js
1. should show Delete button under dropdown-menu
2. should show Delete Blueprint page
3. should show correct deleting blueprint name
4. should close Delete Blueprint page and no blueprint deleted by clicking Cancel button
5. should close Delete Blueprint page and no blueprint deleted by clicking X button
=> Add 5 cases to test delete blueprint feature.

test/end-to-end/pages/editBlueprint.js, test/end-to-end/test/test_editBlueprint.js
1. should have correct filter content label
2. should show correct filtered components name and number
3. should clear filter result by clicking X button on filter label
4. should clear filter result by clicking Clear All Filters link
=> Add 4 cases for filter feature on edit blueprint page.

test/end-to-end/pages/createBlueprint.js, test/end-to-end/pages/editBlueprint.js, test/end-to-end/test/test_createBlueprint.js
This case will simulate user behavior to create blueprint.
1. Input name and description, then create.
2. Select httpd component.
3. Commit changes.
4. Save changes.
5. Check new added blueprint visable on blueprints page.
=> Add create blueprint workflow test.

Dockerfile.metadata, import-metadata.sh
DON'T MERGE just yet. bdcs.rpm rebuild blocked by juhp/cabal-rpm#56
=> Use schema.sql from bdcs.rpm

test/end-to-end/pages/editBlueprint.js, test/end-to-end/test/test_editBlueprint.js
1. Commit button should be in disabled stauts
2. Discard Changes button should be in disabled stauts
3. Commit button should be in enabled stauts
4. Discard Changes button should be in enabled stauts
5. Pending Changes link should not exist
6. Pending Changes link should be displayed
=> Add case to test different button status according to blueprint changes.

test/end-to-end/README.md, test/end-to-end/config.json, test/end-to-end/pages/main.js, test/end-to-end/test/test_blueprints.js, test/end-to-end/test/test_createBlueprint.js, test/end-to-end/test/test_editBlueprint.js, test/end-to-end/test/test_importSanity.js, test/end-to-end/test/test_viewBlueprint.js, test/end-to-end/utils/helper.js
Updates on how the test suite does timeouts because with lorax-composer these have to be extended significantly.
=> Update timeout options

test/end-to-end/pages/changesPendingCommit.js, test/end-to-end/pages/editBlueprint.js, test/end-to-end/test/test_pendingCommit.js
1. should show changes pending commit page by clicking Commit button
2. should show changes pending commit page by clicking pending changes link
3. should show correct pending change content
4. should show correct order of pending changes
5. should not commit by clicking Close button
6. should not commit by clicking X button
7. should commit changes by clicking Commit button
=> Add 7 cases to test Changes Pending Commit page.

test/end-to-end/pages/editBlueprint.js, test/end-to-end/test/test_editBlueprint.js
1. should show correct icon according to component status
=> Add a case to verify icon of avaliable component.

test/end-to-end/pages/blueprints.js, test/end-to-end/test/test_blueprints.js
1. should open Edit Blueprint page by clicking Edit Blueprint button
=> Add case to test Edit Blueprint button in blueprints page

Makefile, core/apiCalls.js, core/constants.js, core/sagas/inputs.js, data/BlueprintApi.js, pages/blueprintEdit/index.js, test/end-to-end/config.json, test/end-to-end/test/test_editBlueprint.js, test/end-to-end/test/test_pendingCommit.js, test/end-to-end/utils/helper.js
=> Use haskell api backend

Makefile, cockpit-composer.spec.in
This is going to be the name of the package for RHEL7, same content,
just a different name, and the Requires on lorax-composer.
=> Add a cockpit-composer-* target

npm-shrinkwrap.json
@dashea, according to your request, I added npm-shrinkwrap.json back. Sorry for inconvenient.
=> Add npm-shrinkwrap.json back.

components/ListView/ComponentDetailsView.js, components/ListView/ListItemComponents.js, pages/blueprint/index.js
Something simple for me to get to know the code a little.
The mock data is quite confusing when trying to see what's still missing.
We probably want empty states for "Changes" and the commit dropdown. If there are already designs for those, I can add them to this PR. 
@andreasn, @jgiardino Did I get everything?
=> Remove mock data

components/Toolbar/ToolbarLayout.js, core/store.js, test/unit/index.norecipes.spec.js
- updates mockState in unit tests to match state updates for Filters
- fixes issue flagged by tests related to propTypes in ToolbarLayout
- fixes issue related to inconsistent quotation marks in core/store.js
=> Unit test fixes for Filter updates

components/Actions/Actions.js, components/Layout/Navigation.js, components/Wizard/WizardView.js
The coverage tool complained about this non-standard (?) syntax and failed.
=> components: Use consistent syntax for handlers

core/reducers/blueprints.js
Created images were not being added to the state.
=> Fix created image not being added to state

Makefile
See https://github.com/weldr/lorax/pull/387/
=> Adjustments to how we start tests with lorax-composer

Dockerfile.buildrpm, Makefile, package-lock.json
Include the translation files in the dist tarball. This also means installing and running zanata as part of generating the dist tarball.
=> Package translations

components/Modal/ManageSources.js, components/Sources/SourcesList.js, components/Sources/SourcesListItem.js, components/Toolbar/BlueprintsToolbar.js, core/actions/modals.js, core/apiCalls.js, core/constants.js, core/reducers/modals.js, core/sagas/modals.js, core/store.js, pages/blueprints/index.js, public/custom.css
This adds a kebab menu on the home page with an action "View Sources". When clicked, a modal displays that lists sources that are defined. For now, this information is read-only, but later we can add functionality for adding and removing custom sources.
=> Add modal for listing sources

pages/blueprints/index.js
=> Don't call compose API on the blueprints page

components/Modal/CreateImage.js, data/NotificationsApi.js, test/end-to-end/pages/toastNotif.js, test/end-to-end/specs/test_viewBlueprint.js
- Removes previous notifications. These weren't accurately reflecting the image creation process.
- Adds notification text for each status type
- Only displays notification for status 'imageWaiting'. The other notifications will be added in a later PR.
=> Update Create Image notifications

components/Pagination/Pagination.js, public/custom.css
Updates make strings translatable but also available to screen readers.
=> Makes strings translatable in pagination for available components

README.md
Small fix to `README.md` to check that the Cockpit's bots are running.
=> README: We're running tests on Cockpit's CI now

test/selenium_start.sh
Now that Cockpit's selenium image with debugging containers landed, only
try and run these.
=> Simplify selenium startup again

test/end-to-end/wdio.conf.js
How to fix it?
Make chrome full screen before test running.
=> Fix flaky issue when running test on chrome.

test/end-to-end/specs/test_editBlueprint.js
If there's one case failed, I can find it according to case name.
=> Remove ForEach to run two test cases but use two separate cases.

test/end-to-end/pages/createBlueprint.js, test/end-to-end/specs/test_editBlueprint.js, test/end-to-end/specs/test_pendingCommit.js, test/end-to-end/wdio.conf.js
That'll be easy for me to debug failed case on chrome.
=> Grab code changes from PR#368 to run test on chrome on this PR.

test/end-to-end/pages/editBlueprint.js, test/end-to-end/specs/test_importSanity.js, test/vm.install
=> Add RHEL-X in welder-web test scenarios.

.tasks, Makefile
=> Trigger the po-refresh bot

package.json
=> package.json: Update history package dependency

package.json
=> package.json: Update react-redux package dependency

package.json
=> package.json: Update react-intl package dependency

Makefile, cockpit-composer.spec.in, io.weldr.cockpit-composer.metainfo.xml
This will make welder-web appear on Cockpit's "Applications" page.
=> Add AppStream metainfo

package.json
=> package.json: Update whatwg-fetch package dependency

package.json
=> package.json: Update redux package dependency

package.json
=> package.json: Update redux-saga package dependency

components/ListView/ComponentInputs.js, components/ListView/LabelWithBadge.js, components/ListView/ListItemComponents.js, components/Toolbar/BlueprintToolbar.js, test/end-to-end/components/AvailableComponents.component.js, test/end-to-end/components/dependencies.component.js, test/end-to-end/components/selectedComponents.component.js, test/end-to-end/pages/EditBlueprint.page.js, test/end-to-end/specs/editBlueprint1.test.js, test/end-to-end/specs/editBlueprint2.test.js, test/end-to-end/utils/commands.js
Add attribute `data-*` in some elements to make element locating easy.
Update test case according to new changes.
Add new case to cover "Selected Components" tab and "Dependencies" tab.
=> Add attribute `data-*` in some elements, update case accordingly, add new case

package.json, test/end-to-end/pages/blueprints.page.js, test/end-to-end/specs/blueprints.test.js, test/end-to-end/specs/createBlueprint.test.js
1. Fix a prettier setting issue to make prettier align with eslint.
2. Add test cases to check duplicated blueprint name error message.
Found a chromedriver issue, no solution but a workaround. https://github.com/webdriverio/webdriverio/issues/1140
=> Fix a prettier setting issue and add test cases.

test/end-to-end/utils/commands.js
This change is to avoid dependence resolving issue in PR #500.
=> Change adding component to blueprint workflow from adding random package to adding "httpd" one.

package.json
=> package.json: Update prop-types package dependency

Makefile, test/vm.install
This update only gets enabled on Fedora and running test on firefox.
=> Update lorax-composer using the updates-testing repository to test it before it enters into stable repo.

po/uk.po
Update translations from Fedora Zanata
=> Update translations from Fedora Zanata

core/reducers/blueprints.js
Commit ad4d916dcad3d2af3a2e8f98cd8ed3598616ee5f missed this specific
occurance.
Closes #605
=> reducers: Fix workspacePendingChanges variable initialization

test/end-to-end/specs/createImage.test.js
This also applies to RHEL 7.7.
=> test: Generalize image format condition for all RHEL 7.x

components/Form/Password.js, components/Modal/UserAccount.js, pages/blueprint/index.js
Closes issues #625 and #626. Also addresses an issue where the user enters a value for the first password field then delete the value. Before this update, the Create button would remain disabled, but instead, it should become enabled again.
=> User account issues

pages/blueprint/index.js
=> Remove new line in encrypted password

package.json
=> package.json: Update jquery package dependency

test/vm.install
Remove disabling selinux on 4.x kernel because lorax-composer fixed this issue already.
=> test: remove disabling selinux on 4.x kernel

.travis.yml, README.md, cockpit-composer.spec.in, package.json, test/end-to-end/specs/blueprints.test.js, test/end-to-end/specs/createImage.test.js, utils/cockpituous-release, zanata.xml
Multiple links where updated including:
* GitHub repo
* Travis builds
* codecov
* name for releasing in copr
* zanata proeject name
=> [no-test] Rename project from welder-web to cockpit-composer

components/EmptyState/EmptyState.js, components/EmptyState/EmptyStateInactive.js, components/Modal/ManageSources.js, components/Toolbar/BlueprintsToolbar.js, core/actions/blueprints.js, core/reducers/blueprints.js, core/sagas/blueprints.js, core/store.js, pages/blueprints/index.js, public/custom.css, test/check-application, test/end-to-end/pages/blueprints.page.js, test/end-to-end/specs/api.test.js, test/end-to-end/specs/blueprints.test.js, test/end-to-end/specs/createBlueprint.test.js, test/end-to-end/specs/createImage.test.js, test/end-to-end/specs/createUserAccount.test.js, test/end-to-end/specs/editBlueprint1.test.js, test/end-to-end/specs/editBlueprint2.test.js, test/end-to-end/specs/sources.test.js, test/end-to-end/specs/viewBlueprint.test.js, test/end-to-end/utils/commands.js, test/end-to-end/wdio.conf.js, test/vm.install
Closes #460 
These updates include a custom error message when the error "not-found" is returned. The error state and actions are based on [similar UI in cockpit](https://github.com/cockpit-project/cockpit-podman/commit/24665af7d0f7d2529b34f0797eeba380ec60e4a0).
The second commit also prevents the empty state message from displaying while waiting for the blueprint contents to load.
=> error state with option to start lorax-composer

components/ListView/ListItemImages.js, core/composer.js, public/custom.css
Especially when some image build failed it's usefull to be able to see
from the composer UI the anaconda logs.
This commit enables this functionality, by having a link for showing the
logs in each image.
=> Add link to show the anaconda.log from the compose build process

components/ListView/SourcesListItem.js, components/Modal/ManageSources.js, test/end-to-end/pages/sources.page.js, test/end-to-end/specs/sources.test.js
1. Add data-* and id attributes to make search page element easy.
2. Add test case for manage sources page.
=> test: Add test case for manage sources page

test/end-to-end/pages/createBlueprint.page.js, test/end-to-end/specs/createBlueprint.test.js
1. blueprint name with invalid character should not be allowed
2. all invalid characters should be reported with error message
=> test: Add blueprint name character verification case

test/end-to-end/components/AvailableComponents.component.js, test/end-to-end/components/selectedComponents.component.js, test/end-to-end/pages/EditBlueprint.page.js, test/end-to-end/pages/blueprints.page.js, test/end-to-end/specs/editBlueprint2.test.js
1. run scrollIntoView() from javascript to make element visible
2. click element directly by javascript if scrollIntoView() does not work in some cases
=> test: Work around off screen element issue on Edge

core/actions/blueprintPage.js, core/reducers/blueprintPage.js, core/store.js, data/NotificationsApi.js, pages/blueprint/index.js, routes.json
…tabs
There is not any benefit to keep the active tabs in the store.
These information should be kept in the state of the component that
creates the Tabs and not somewhere in the global state, but we are using
Tabs as uncontrolled component here, so we don't need to maintain the
state of the active tabs at all.
=> Cleanup Tabs in Blueprints page

package.json
=> package.json: Update shortid package dependency

pages/blueprint/index.js, pages/blueprintEdit/index.js
Remove api calls from render functions so the same call isn't placed multiple times without waiting for a response.
=> Fix repeat api calls

Dockerfile.buildrpm, Makefile, README.md, cockpit-composer.spec.in, io.weldr.cockpit-composer.metainfo.xml, test/end-to-end/pages/login.page.js, test/end-to-end/utils/commands.js
@martinpitt do we need to do something special in the spec file to make updates work correctly?
=> Expose Image Builder on /composer, not /welder

package.json
=> package.json: Update @patternfly/react-icons package dependency

components/Modal/ManageSources.js, components/Modal/UserAccount.js, pages/blueprint/index.js
eslint error like:
```
342:31  error  Curly braces are unnecessary here react/jsx-curly-brace-presence
```
=> Fix eslint error 'Curly braces are unnecessary here'

package.json
=> package.json: Update core-js package dependency

components/ListView/ComponentDetailsView.js, components/ListView/ComponentInputs.js, components/ListView/ComponentSummaryList.js, components/ListView/ComponentTypeIcons.js, pages/blueprintEdit/index.js, public/custom.css, test/end-to-end/components/AvailableComponents.component.js, test/end-to-end/components/selectedComponents.component.js, test/end-to-end/pages/EditPackages.page.js
This PR addresses remaining items in #804 and is based on updates made in PR #802.
The list of available components and list of dependencies in the details of an expanded component are migrated from the PF3 to PF4 datalist component.
=> Pf4 components list view secondary

components/ListView/BlueprintContents.js, components/ListView/ComponentDetailsView.js, components/ListView/ComponentsDataListItem.js, components/ListView/ListItemImages.js, components/Modal/CreateBlueprint.js, components/Modal/CreateImage.js, components/Modal/DeleteBlueprint.js, components/Modal/DeleteImage.js, components/Modal/EditDescription.js, components/Modal/ExportBlueprint.js, components/Modal/ManageSources.js, components/Modal/PendingChanges.js, components/Modal/StopBuild.js, components/Modal/UserAccount.js, core/composer.js, core/selectors.js, package.json, pages/blueprint/index.js, pages/blueprintEdit/index.js, pages/blueprints/index.js
Fix the formatting across the project to prevent a build failure due to eslint. I am currently unsure what changed that makes these changes necessary but this PR will build locally for me.
=> Update formatting for eslint requirements

package.json
=> package.json: Update core-js-compat package dependency

package.json, po/cs.po
Push only .pot file.
Fixes #852
=> po: Do not push translation files into Zanata

test/end-to-end/package.json
See https://github.com/webdriverio/webdriverio/issues/4934
=> test: Lock down wdio packages

po/de.po, po/es.po, po/fr.po, po/ja.po, po/ko.po, po/sk.po, po/tr.po, po/zh_CN.po
Update translations from Fedora Weblate
=> Update translations from Fedora Weblate

package.json
=> package.json: Update regenerator-runtime package dependency

README.md, cockpit-composer.spec.in, components/EmptyState/EmptyStateInactive.js, test/end-to-end/components/Details.component.js, test/end-to-end/pages/blueprints.page.js, test/end-to-end/specs/api.test.js, test/end-to-end/specs/blueprints.test.js, test/end-to-end/specs/createBlueprint.test.js, test/end-to-end/specs/createImage.test.js, test/end-to-end/specs/editPackages2.test.js, test/end-to-end/specs/imageBuilding.test.js, test/end-to-end/specs/sources.test.js, test/end-to-end/utils/commands.js, test/end-to-end/wdio.conf.js, test/vm.install
This is the same as PR #839 but to merged to master.
Per @larskarlitski 
>osbuild-composer is a drop-in replacement for lorax-composer, providing
the same API:
https://github.com/osbuild/osbuild-composer
Switch the dependency, documentation, and the name of the service for
the "Start Service" page.
=> Switch to osbuild-composer backend for master

components/Modal/CreateImageUpload.js, main.js, package.json, public/custom.css, test/verify/check-image
Add ability to upload vhd images to Microsoft Azure in the CreateImageUpload wizard.
This is dependent on #946 and #953
=> Add Azure Upload Support

test/verify/run-tests
Flake8 checking failed due to E302 error
https://travis-ci.org/github/osbuild/cockpit-composer/jobs/685910072
=> test: Add one more blank line to fix flake8 E302 error

package.json
=> package.json: Update @patternfly/react-styles package dependency

README.md
@jgiardino is it understandable how things work? Or are there some thing, that are not clear?
=> Update i18n section in README

components/ListView/ComponentDetailsView.js, components/Toolbar/FilterInput.js, components/Toolbar/ToolbarLayout.js, test/verify/check-blueprint
Fix translations for blueprint components and filtering.
=> Fix translations

components/Modal/CreateImageUpload.js, public/custom.css
Add popover help strings for azure upload. This is dependent on #954
=> Azure help strings

components/Form/Password.js, public/custom.css, test/verify/check-custom
This removes the password quality check from the Create User Account modal.
_I forgot to include in the original commit:_
fixes #985
🤦
=> Password verification

package.json, pages/blueprint/index.css, pages/blueprint/index.js, test/verify/check-custom
=> Port blueprint customizations users table to PF4

components/ListView/ComponentDetailsView.js
In the component details view the handleUpdateComponent is called in an arrow function. This function needs to be wrapped by curly brackets.
This should help with #1009
=> components: fix update component arrow function

components/ListView/ListItemImages.js, test/verify/check-image
This reverts commit 0917f771a97cdda7f0147c0de652e84e7a6bc1a4. This reenables the ability to cancel/stop a compose.
=> Revert "components: remove stop option"

components/Wizard/AzureDestinationStep.js, components/Wizard/ReviewStep.js, test/verify/check-image
Check that the azure fields and entered values are shown as expected. Also, check that the help messages have the correct text.
=> test: add wizard tests for azure steps

components/EmptyState/EmptyState.js, components/ListView/BlueprintContents.js, components/ListView/ComponentSummaryList.js, components/ListView/ListItemImages.js, components/Wizard/CreateImageUpload.js, components/Wizard/ImageStep.js, components/Wizard/ReviewStep.js, package.json, pages/blueprintEdit/index.css, pages/blueprintEdit/index.js, public/custom.css, test/verify/check-image, test/verify/check-service
Patternfly 4 is upgraded. The patternfly provdided script pf-codemods was applied to fix component and property name changes. This will remain a draft PR until all elements have visual parity with the old version of patternfly 4.
=> package: upgrade patternfly 4 to new major release

components/ListView/ListItemImages.js, components/ListView/ListItemUploads.js, components/Wizard/ReviewStep.js, core/composer.js, core/sagas/composes.js, pages/blueprint/index.js
The image and upload list now map from image/provider type to a display label. This conversion mimics the labels used in the CreateImageUpload wizard.
Closes #959
=> Fix upload type capitalization

Makefile, components/Toolbar/FilterInput.js, po/fr.po, po/ja.po, po/ko.po, po/zh_CN.po, test/vm.install
Picked change from #1087 
Also updated translations which were provided by localization team. It still needs `fr.po` which will be available on Monday. Then I'll update the last commit.
If there is any other change that you want to get into 8.3 now is the time :) I went through commits in master that did not make it in and nothing stood up.
DO NOT MERGE YET, lets wait for the fr.po file.
=> [Backport] Update rhel8 branch

README.md
This is mostly an excuse to trigger tests on the current rhel-8-3 image, to compare with the refresh for https://github.com/cockpit-project/bots/pull/1256
=> README.md: Grammar fix

test/README.md, utils/cockpituous-release
Stop releasing into fedora 31 since it is going EOL.
=> Remove fedora 31 release

components/Form/TextInlineEdit.js, components/ListView/ComponentDetailsView.js, components/Modal/CreateBlueprint.js, components/Modal/DeleteBlueprint.js, components/Modal/ExportBlueprint.js, components/Modal/UserAccount.js, components/Notifications/Notification.js, components/Wizard/CreateImageUpload.js, pages/blueprintEdit/index.js
Cherry-picked from master commit 7fc34e1.
=> eslint: fix lint issues with function order

package.json
I just did `git pull upstream master` while in `rhel-8` branch.
This is needed synce current `rhel-8` branch does not build:
```
ERROR in ./node_modules/@patternfly/react-core/dist/esm/components/Touchspin/Touchspin.js
```
=> [rhel-8] Sync up master branch with rhel-8 branch

cockpit-composer.spec.in, components/Wizard/CreateImageUpload.js, components/Wizard/ImageStep.js, core/sagas/composes.js, test/verify/check-image
This reverts commit 08e46cdb3ef761f2f4d6d75c97e90d786ca86432. VMWare is now a selectable upload type.
=> Add new edge image type support and validation, reenable vmware

test/verify/check-image
Also select logs using selector
=> test: readd nondestructive

components/Wizard/CreateImageUpload.js, pages/blueprint/index.js, pages/blueprints/index.js
=> Improve loading state

Makefile, README.md, lib/patternfly/_fonts.scss, lib/patternfly/patternfly-4-cockpit.scss, lib/patternfly/patternfly-cockpit.scss, lib/patternfly/patternfly-overrides-variables.scss, lib/patternfly/patternfly-overrides.scss, test/README.md
Outstanding is the weblate update.
=> various master → main changes

.github/workflows/release.yml
Any tag starting with a v will be released.
=> workflows: release tags now start with a v

components/ListView/BlueprintsDataList.js, components/Wizard/CreateImageWizard.css, components/Wizard/CreateImageWizard.js, components/Wizard/ImageCreator.js, components/Wizard/formComponents/BlueprintName.js, components/Wizard/formComponents/CustomSubmitButtons.js, components/Wizard/formComponents/ImageOutputSelect.js, components/Wizard/steps/imageOutput.js, components/Wizard/steps/index.js, core/sagas/composes.js, package.json
This is a very minimal migration of the existing wizard to ddf. No customizations or review. Just basic image selection and creation.
=> Ddf wizard

Makefile, package.json, webpack.config.js
This also involved upgrading several webpack loaders and dependencies.
=> Upgrade to webpack v5

components/Wizard/CreateImageWizard.css, components/Wizard/CreateImageWizard.js, components/Wizard/ImageCreator.js, components/Wizard/formComponents/BlueprintName.js, components/Wizard/formComponents/ImageOutputSelect.js, components/Wizard/formComponents/Review.js, components/Wizard/formComponents/TextFieldCustom.js, components/Wizard/steps/awsAuth.js, components/Wizard/steps/awsDest.js, components/Wizard/steps/details.js, components/Wizard/steps/imageOutput.js, components/Wizard/steps/imageOutputStepMapper.js, components/Wizard/steps/index.js
Enable uploads to AWS and add improvements to details step.
=> Add aws upload support

test/verify/check-custom
=> Test: Fix check-custom tests

test/verify/check-service
=> Test: Fix check-service testing

components/Wizard/CreateImageWizard.js, components/Wizard/steps/imageOutput.js, test/verify/check-wizard
The image output step is now a function which returns a json schema. This functional component can use the useIntl() hook to connect the step to the translations provider.
=> wizard: translate image output step

components/Wizard/formComponents/Packages.js
Previously, only the blueprint name was available in the form state.
Now, the full blueprint is available in the form state - and includes
the list of selected packages. This allows us to greatly simplify the
useEffect() hook that is used to set the chosenPackages state, as the
list of chosen packages can simply be read directly from the blueprint.
Previously the blueprint had to be depsolved.
Note that an async api call is still required to fetch the package
summaries.
This commit also fixes #1494. This commit fixes a bug where if a package
was searched for in `Available packages` that was in the list of
selected packages, it would incorrectly appear in the `Available packages`
list if available package list was fetched before the chosenPackages
state was set. This was because before …
=> Wizard: Package step improvement and bugfix

src/components/Modal/ImportBlueprint.js
=> Modal: allow ImportBlueprint modal to be editable

src/components/Table/BlueprintTable.js, src/pages/blueprintList.js
Fixes #1686.
This reduces the amount of the empty space in the list of the blueprints.
=> Table: Reduce empty space in the blueprint list

src/components/Table/ImageTable.js
The Download logs button now works as the images one does. It uses cockpit to transport the logs from weldr api to the users browser.
Fixes #1683
=> Table: fix download button for logs

src/components/Modal/SourceCardModal.js
=> Fix source card modal

src/components/Modal/FirewallCard.js
=> FirewallCard: accurately display zones

src/App.js, src/api.js, src/components/EmptyStates/APIEmpty.js, translations/en.json
If the API isn't started the user is prompted to start it.
=> EmptyStates: add an api empty state

README.md
This guide is specifically for performing a visual install inside a VM on a MacOS host.
=> README: add VM install instructions

src/App.js
Fetch blueprints and images every 30 seconds in case of changes via the cli
=> App.js: add polling for blueprints and images (COMPOSER-2153)

src/helpers.js
This commit sanitizes the form data and makes sure that the values of
the form fields are truly empty. For example, the filesystem customization
option was being initialized to an empty array. This was causing `edge-commit`
and `edge-commit` image types to break since they are not allowed
filesystem customizations.
Additionally, this commit ensures that all the fields are undefined if they have
not been set. This ensures that the blueprint is saved correctly and the below
no longer happens:
```
[customizations]
[customizations.kernel]
append = ""
[customizations.timezone]
[customizations.locale]
[customizations.firewall]
[customizations.firewall.services]
[customizations.services]
[customizations.fdo]
[customizations.ignition]
[customizations.ignition.firstboot]
```
=> blueprintwizard: remove empty customizations (RHEL-28534)

Makefile, test/files/rhel-10.json, test/verify/check-blueprintList, test/verify/check-blueprintWizard, test/verify/check-imageWizard, test/verify/composerlib.py, test/vm.install
322 includes the migration from CDP to BiDi browser automation, and will require some test changes.
=> test: cockpit testlib 321 & support for rhel-10 and centos-10 testing

packit.yaml
- new targets
- separate main and release coprs
- remove metadata indirection
=> packit.yml: various improvements

test/files/rhel-9.6.json, test/vm.install
Unblocks cockpit-project/bots#6977.
=> test: add rhel-9.6 nightly repositories

README.md
Mention that it's obsolete and point to the replacement.
=> README: Mention that the project is abandoned
