osbuild/cockpit-composer

components/ListView/ListItemExpandRevisions.js
pages/recipe/index.js
public/custom.css

https://trello.com/c/ELJLX8Fg/183-3-comments-and-revisions-rough-draft-ui-design
Updates include draft UI for the following:
- ability to capture comments about the recipe. I should be able to see these comments on the Details tab only
- showing comments per Revision on the Revisions tab is deferred until it becomes a known requirement
- this update also includes removing the ability to toggle to a different revision on the Details tab. This feature will only be available on the Components tab. And information for different revisions will be available on the Revisions tab
- visual differentiation between current revision and past revisions
- visible actions per revision for editing the recipe and creating the composition

Recipe revisions

---

components/Pagination/Pagination.js
pages/recipeEdit/index.js
public/custom.css

This update includes a pagination control above the list of available inputs.
The three main elements of this control are:
- previous page button - Disabled if the current page is the first page. Allows the user to navigate to the previous page.
- next page button - Disabled if the current page is the first page. Allows the user to navigate to the previous page.
- page input - Allows the user to specify a page to navigate to. Does not accept a value other than empty or a number within the page range. If the user changes the value then exits the field without submitting, the value resets to match the current visible page.
These controls make updates to how inputs are set in state. The state is now an array of arrays, with each array being the set of items in that page.
These controls also …

Pagination

---

Dockerfile
core/utils.js
entrypoint.sh
public/js/config.js

Add a switch to make createUrl just return the url, not add the scheme,
host or port.
Split the API_URL into component pieces for new config.js, ALL parts
must be present when setting it.
This also displays the modified config.js when starting.
Startup of nginx has been moved to CMD in the Dockerfile so that you can
start up the container without overriding entrypoint. Just pass
/usr/bin/bash to run bash instead of nginx

When running the API behind a proxy it needs to use relative URLs

---

pages/recipeEdit/index.js

When preventDefault and stopPropagation were
added to the pagination, they prevented the default
behavior of entering a new value in the input field.
I moved these to only the cases where the user is
hitting the enter key when the input has focus or
using the pagination buttons, but not when hitting
any other key (e.g. like "9" to navigate to page 9).

fixing a bug related to pagination

---

components/ListView/RecipeListView.js
components/Modal/CreateRecipe.js
data/RecipeApi.js
pages/recipe/index.js

- Recipes page was updated so that expand/collapse ability is removed (previously a hard-coded composition was listed in the expanded section of a recipe list item). For now, the code to expand/collapse is just commented out, since this will probably be added back in.
- Create Recipe dialog has updates related to not showing error messages on Cancel, and removing the background color on Save
- Ability to edit the description was added to the Recipe page. On the recipe page, Details tab, clicking the description or Edit icon next to the description displays an input field. When the description is modified, the change can be saved or canceled. If saved, the recipe is immediately updated in the database.

UI refinements related to creating/viewing recipes

---

components/ListView/ComponentDetailsView.js
components/ListView/ListItemComponents.js
data/MetadataApi.js
pages/recipeEdit/index.js

This enables the Edit action that displays in the kebab menu of a component listed under Selected Components in the Edit Recipes page.
Before this PR, you could click the component name to navigate to the details view, then click the Edit button to display the form for selecting a different version-release. This is still available.
But now, clicking Edit in the kebab on a component list item will navigate to the details view with the form automatically visible.

implementing Edit action in component li kebab

---

components/ListView/RecipeListView.js
core/constants.js
data/RecipeApi.js
pages/recipes/index.js

For the purposes of usability testing, this PR includes an action "Archive" that deletes a recipe. The "Archive" action is needed for getting feedback. The delete action is used to remove the recipe. This is not intended to be a final implementation.
The action "Archive" displays in the kebab on a recipe list item. 
NOTE: these updates were implemented using the updates included in this PR: https://github.com/weldr/bdcs-api-rs/pull/58

Recipe delete

---

components/Layout/Header.js
components/ListView/ComponentDetailsView.js
components/ListView/ComponentSummaryList.js
components/ListView/ListItemComponents.js
components/ListView/ListItemCompositions.js
components/ListView/ListItemExpandRevisions.js
components/ListView/RecipeListView.js
components/Toolbar/Toolbar.js
pages/recipe/index.js
pages/recipeEdit/index.js
pages/recipes/index.js

These are updates related to general UI clean up for user testing:
There are non-functional links that are included in the UI for the purposes of user review. But when the user clicks on one of these links, the user is redirected to the home page (i.e. "Overview") due to the `href="#"`. For any link that is not implemented yet, these href attributes have been removed, to avoid any unnecessary confusion during user testing.
Values for "Revision" are replaced with a hard-coded value of "3" so that it matches the mock data. This is to avoid any confusion during user testing.
On the Recipe page, Revisions tab, classes for the expand/collapse arrow are updated to fix a sizing issue. When the down arrow became visible after expanding a list item, the arrow was not the correct size.

removing href from nonfunctional links

---

public/custom.css

In a list view there list items can be expanded, if the content are
includes a nested list, this sets a max height so that the parent list
item doesn't get too tall.
An example of this is any component list item (Selected Component or Dependency) on either the Recipe page or Edit Recipe page. The nested list is the list of Dependencies that displays in the expanded content area of a component list item.

Includes scrollbars for nested lists

---

data/RecipeApi.js
pages/recipeEdit/index.js

When clicking Save on Edit Recipe page, a saving
notification should display immediately. This update
triggers the Layout component to reload and display
the saving notification. When the recipe is saved,
the 'saving' notification is then replaced with a 'saved'
notification.

Fixing issue with 'Saving' notification

---

data/RecipeApi.js

@henrywang, this fixes the issue you had noted before about Edit Description and navigating to the Edit Recipe page.
Steps to reproduce the issue being fixed:
1) edit the description on the Recipe page, Details tab
2) navigate to the Edit Recipe page
3) navigate back to the Recipe page
Results:  the previous description before the edit
is visible. But clicking reload on the page will show the
description that was saved.
This issue occurred because the recipe data gets cached,
but the cached description wasn't getting updated upon
editing the description.

fixes issue with updating cached description

---

components/Toolbar/Toolbar.js

Adds a class to the dropdown so that it displays right-aligned
so that the contents aren't cut off by the edge of the screen.

displays Edit Rec. toolbar kebab menu right-aligned

---

test/end-to-end/Dockerfile
test/end-to-end/README.md
test/end-to-end/entrypoint.sh
test/end-to-end/package.json

Run docker image as run end-to-end test.
Move eslint and its plugin from dependencies to devDependencies.
Update README.md with Running end-to-end test in Docker section added.

Package end-to-end test into a docker image.

---

components/ListView/ListItemCompositions.js
components/ListView/ListItemExpandRevisions.js
components/Toolbar/Toolbar.js
data/NotificationsApi.js
pages/recipe/index.js

This work is in preparation for ability to export a manifest file, but for now, just updates the action label and where the action is included.
Updates include:
- Remove Export action and kebab from Composition
Created notification
- Replace all instances of 'Export Recipe' with just
'Export'. This action might later be used for different
export options, but for now will just export a manifest
file when the backend work for the manifest file is
completed
- On Revisions tab, moved 'Export' and kebab from toolbar
and added to each individual Revision list item

Export recipe

---

test/end-to-end/test/test_createRecipe.js
test/end-to-end/test/test_editRecipe.js
test/end-to-end/test/test_recipes.js
test/end-to-end/test/test_viewRecipe.js

That will not increase case running by adding wait selector step.
From my debug result, all of wait selector step just cost 0ms.
`nightmare queueing action "wait" +0ms`

Add wait selector step when switching pages to make case more stable.

---

Dockerfile
test/end-to-end/Dockerfile

Currently I'm seeing the following error lcoally and in Travis:
gpg: requesting key 7E37093B from hkp server ha.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
with this patch I'm able to import the offending key:
gpg: requesting key 7D83545D from hkp server pool.sks-keyservers.net
gpg: key 7D83545D: public key "Rod Vagg <rod@vagg.org>" imported
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   2  signed:   2  trust: 0-, 0q, 0n, 0m, 0f, 2u
gpg: depth: 1  valid:   2  signed:   0  trust: 0-, 1q, 0n, 1m, 0f, 0u
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
The hostname pool.sks-keyservers.net is also the official one listed
in Node's README!

Fix for GPG key timeout error

---

Makefile
test/end-to-end/package.json
test/end-to-end/pages/editRecipe.js
test/end-to-end/test/test_importSanity.js

This is in addition to the import sanity tests on the backend. We can always add more content tests on the frontend if needed.

Add e2e sanity test for imorted content

---

components/ListView/ListItemExpandRevisions.js
components/ListView/RecipeListView.js
components/Modal/ExportRecipe.js
components/Toolbar/Toolbar.js
pages/recipe/index.js
pages/recipeEdit/index.js
pages/recipes/index.js
public/custom.css

Includes updates for:
https://trello.com/c/XTe8z9Ef/261-3-manifest-file-include-link-in-ui
Updates include:
- Export action that displays on Recipes, Recipe and Edit
Recipe pages opens a modal dialog
- dialog includes 'Export as' select menu with only one
option for now, 'Text'
- For the 'Text' option, a textarea displays listing all
components as name-version-release, with the total
number displayed below
- For the 'Text' option, a Copy button displays that will copy
the contents of the textarea to the clipboard
- When displaying the dialog on the Recipes page, a
spinner displays in place of the textarea while the contents
are being retrieved

Ability to see recipe manifest via Export action

---

Makefile

According to PR #11 of weldr/welder-deployment, the mddb will be mount with host folder.

Update mddb volume map folder to host folder

---

test/end-to-end/test/test_importSanity.js

1. Add wait time before getting total count to make this number loaded.
2. Add a before hook to check exist of metadata.db file to avoid useless
metadata.db generated by new dqlite3.database command.

Update importSanity test with some changes:

---

Makefile

This is a pre-requirement for #125. It modifies the build sequence so that web and end-to-end images don't build the welder/fedora:25 and welder/bdcs-api-rs:latest images locally and instead pull them from Docker Hub. This saves us about 5 minutes in execution time.

Manually build all docker containers using the images from Docker hub

---

.dockerignore
.travis.yml
Dockerfile
Dockerfile.nodejs
Makefile
test/end-to-end/Dockerfile

This is an updated version of #125 which pulls the latest images from Docker hub and tries to reuse them as cache. 
NOTE: as in my PR for bdcs-api-rs here we see the npm install happening again inside the image although there's no need for that. I'm not quite certain what causes this but I think it will be resolved once the changes get merged to master and we start pushing to Hub from CI.

Try to optimize e2e tests by re-using images from Docker hub

---

.travis.yml
Dockerfile
Dockerfile.with-coverage
Makefile
README.md
package.json
test/end-to-end/.eslintrc
test/end-to-end/Dockerfile
test/end-to-end/README.md
test/end-to-end/test/test_createRecipe.js
test/end-to-end/test/test_editRecipe.js
test/end-to-end/test/test_importSanity.js
test/end-to-end/test/test_recipes.js
test/end-to-end/test/test_viewRecipe.js
test/end-to-end/utils/coverage.js
webpack.config.js

This is all the works necessary to support this. See the commit logs for more details but it boils down to:
1) Instrument the application code (main.js, pages, etc) with babel-plugin-istanbul. Only do this if --with-coverage has been passed on the command line otherwise we mess up unit tests (more precisely coverage from them)
2) In e2e tests make a slight modification how we chain and terminate Nightmare calls. This is necessary b/c we have to bring that coverage information from the browser scope (the page under test) to nodejs scope (the code doing the testing) and finally close the electron instance running the application.
**WARNING**: the above requires a bit of change in the way tests are written, in particular don't call `.end()` and `done()` but instead call the coverage handling …

Enable end-to-end test coverage

---

public/manifest.json

Increase order priority so that Welder does not appear as the first
thing in the top menu bar, even before Cockpit's own dashboard.
Also drop erroneous tab character.

Adjust Cockpit manifest order

---

main.js
package.json
public/index.ejs
public/manifest.json
webpack.config.js

Pull in jQuery, jquery.matchHeight, bootstrap, and bootstrap-select via
npm and webpack instead of external URLs. Drop these from
Content-Security-Policy.
---
Official cockpit modules must have a "strict" C-S-P without external code and also without `unsafe-inline` and `unsafe-eval`. This PR gets rid of the former.
I kept jQuery as separate .js files, I think (for some reason, not sure why) that is a common pattern. However, bootstrap should be fine to get pulled in via `import` and bundled via webpack (so it ends up in the bundled main.js), and in my manual tests that seems to work.

Drop references to external code

---

Makefile

The tests don't clean up behind themselves very well and cannot currently be run more than once without manual steps. There are still running containers, a docker network,  and the db download file handling is broken.
This isn't perfect yet, but at least makes things better.

Fix running integration tests multiple times

---

components/ListView/DependencyListView.js
components/Toolbar/Toolbar.js
core/actions/sort.js
core/reducers/index.js
core/reducers/sort.js
core/selectors.js
core/store.js
pages/recipe/index.js
pages/recipeEdit/index.js
pages/recipes/index.js

Recipes, components, and dependencies can be sorting by name in either ascending or descending order on the recipes page, recipe page, and editRecipe page. The tests all pass locally and I am unsure why they fail on travis.

Sorting PR

---

package.json
run.js

The firebase-tools NPM module and its dependendies take over 230 MB, and
for normal building, development, and CI it's not necessary. Thus move
it out of package.json and install it on demand for "npm run publish".

Only install firebase-tools on demand

---

core/constants.js
core/sagas/inputs.js
core/store.js
core/utils.js
package.json

This triggers a few errors for unused variables, trailing commas in
function arguments, but most importantly a missing `yield` in
core/sagas/inputs.js (see issue #151). Tone down that error into a
warning for the time being, until this gets fixed properly.
---
I stumbled over these when trying to build welder-web in Cockpit. That has these eslint errors on, so the build failed due to these.

Enable recommended eslint checks and fix resulting errors

---

.travis.yml

1. Remove duplicate condition limitation.
1. Keep nyc on @11.1.0 to fix issue - "nyc report" generates "Unknown" code coverage report for e2e test, but not for cockpit-test.
The issue analysis can be found from: https://trello.com/c/IjYvUgcc/429-automation-bugnyc-report-generates-unknown-code-coverage-report-for-e2e-test-but-not-for-cockpit-test

E2e cov fix

---

components/Layout/Header.js
components/Layout/Layout.js
pages/recipe/index.js
pages/recipeEdit/index.js
pages/recipes/index.js
public/index.ejs

Now that the Overview and Users menu entries are gone, "Recipes" is the only one left and thus the navigation bar is currently unused. I left it in the code for now, but not show it. (We can clean up the unused code later).
Also, the header bar is redundant in Cockpit, so hide it there.

Drop nav bar, and hide header bar in Cockpit

---

package.json

The dependency was added in 71a63b230d51 without a particular reason,
thus presumably to just whichever version was current at that time.
However, Cockpit currently uses (and exposes as part of its API) jQuery
2.x only, so lower the minimum version.
----
I went through all the pages, and everything seems to work normally. I also locally ran the tests.

Lower required jquery version to 2.1+

---

components/Layout/Layout.js
components/Link/Link.js
components/ListView/ComponentDetailsView.js
components/ListView/ComponentSummaryList.js
components/ListView/ListItemComponents.js
components/ListView/ListItemRevisions.js
components/ListView/RecipeContents.js
components/ListView/RecipeListView.js
components/Modal/CreateComposition.js
components/Modal/CreateRecipe.js
components/Modal/PendingChanges.js
components/Notifications/Notification.js
components/Pagination/Pagination.js
components/Tabs/Tabs.js
core/reducers/inputs.js
core/reducers/modals.js
core/reducers/recipePage.js
core/reducers/recipes.js
core/reducers/sort.js
core/router.js
main.js
package.json
pages/error/index.js
pages/recipe/index.js
pages/recipeEdit/index.js
pages/recipes/index.js

We don't want to condone arbitrary JavaScript syntax proposals which
haven't been standardized yet. So drop the stage-1 babel preset and
replace it with the explicit two features that the code currently uses:
object spreads and class properties.

Avoid using non-standardized ECMAScript features

---

pages/recipe/index.js
test/end-to-end/pages/viewRecipe.js
test/end-to-end/test/test_viewRecipe.js

The actions Edit Recipe, Create Composition, and Export should not display
below the tabs as tab-level actions, but instead display in the page header as
page-level actions. The Search icon that displays in the toolbar for some of
these tabs is non-functional and should be removed. Finally, if these changes
result in any of the tabs having an empty toolbar, then the toolbar should be
removed.

Move/remove actions on Recipe page

---

package.json

Commit fc8cff732bb (PR #154) lowered the jquery version, but there is
still a second one in devDependencies. Drop it.
----
This isn't the most important thing in the world, but I'm still struggling with lots of UI bugs when building from Cockpit due to dropdowns and dialogs having *two* event handlers attached: one directly through jquery, the other through dropdown.js. I'm trying to elimate as many differences as possible to track this down.

Drop duplicate jquery from package.json

---

test/end-to-end/test/test_createRecipe.js
test/end-to-end/test/test_editRecipe.js
test/end-to-end/test/test_importSanity.js
test/end-to-end/test/test_recipes.js
test/end-to-end/test/test_viewRecipe.js
test/end-to-end/utils/apiCall.js

The integration test's `serviceCheck()` previously caught errors (if the
checked services like bdcs and welder-web are not running) and just
called the `done()` callback, but that does not care about the returned
value - in particular if that is an exception. This causes unhelpful
test failure output and makes the entire `serviceCheck()` call rather useless.
Instead, directly return the two involved promises instead of using a
`done` callback, to let jest deal with it properly (see
http://facebook.github.io/jest/docs/en/setup-teardown.html)
Drop the unused `webCheck()` and `apiCheck()` methods.

Don't ignore failed serviceCheck in tests

---

test/end-to-end/README.md
test/end-to-end/test/test_createRecipe.js
test/end-to-end/test/test_editRecipe.js
test/end-to-end/test/test_importSanity.js
test/end-to-end/test/test_recipes.js
test/end-to-end/test/test_viewRecipe.js
test/end-to-end/utils/coverage.js

Slurping in utils/coverage.js via a manual file read and `eval()` is a
big and unnecessary hack. Turn it into a proper function instead.

Replace eval(coverage.js) in tests with proper import

---

components/CardView/CardView.js
public/manifest.json

There are no inline HTML `on*=""` event handlers and no `<script>` tags.
Inline `style=` was only being used in CardView.js where it does not
actually make any visual difference, so just drop that.

Drop unsafe-inline from Cockpit Content-Security-Policy

---

Makefile

Commit 147cf6e62 moved the metadata.db from a Makefile dependency to an
unconditional command in the `shared` target. As the latter is phony,
this leads to unnecessarily downloading the metadata for every test run.
Revert that bit.
CC: @henrywang, can you please review/land?

tests: Fix metadata.db download regression

---

components/CardView/CardView.js
components/Layout/Navigation.js
components/Layout/PfBreakpoints.js
components/Layout/PfVerticalNavigation.js
components/ListView/ComponentDetailsView.js
components/ListView/ComponentInputs.js
components/ListView/ListItemComponents.js
components/ListView/ListItemRevisions.js
components/ListView/RecipeListView.js
components/Modal/CreateComposition.js
components/Modal/CreateRecipe.js
components/Modal/ExportRecipe.js
components/Modal/PendingChanges.js
components/Wizard/Wizard.js
components/Wizard/WizardView.js
package.json
pages/recipeEdit/index.js

Don't ignore undefined "$" references (jQuery) globally in eslint, as
that cannot be done when building from Cockpit. Declare it per-file
instead.
----
In Cockpit we avoid using jQuery in new code, and it is really discouraged to use *both* React and jQuery in the same module. Thus we don't want a blanket exception for it in eslint, and this makes it easier to track the jQuery removal from welder-web code.

Explicitly eslint-declare jQuery where needed

---

components/Modal/PendingChanges.js
components/Toolbar/Toolbar.js
core/actions/modals.js
core/actions/recipes.js
core/reducers/modals.js
core/reducers/recipes.js
core/sagas/inputs.js
core/selectors.js
core/store.js
pages/recipe/index.js
pages/recipeEdit/index.js
pages/recipes/index.js
test/end-to-end/pages/editRecipe.js
test/end-to-end/test/test_editRecipe.js
test/unit/index.norecipes.spec.js

This PR meets the UI Acceptance Criteria of:
- When a change is made to a recipe, then the number of pending changes displayed next to the Save button is incremented.
- When no pending changes exist, then actions for Save, Discard, View and Comment are not available (buttons are disabled, pending changes text and link are not visible).
- Given one or more pending changes exist, when the user clicks the link "View and Comment", the pending changes are listed in the modal.
- When the user hits Save, then pending changes are committed to the recipe
- The modal dialog includes a comment field
- Undo and Redo actions
In regards to the failed test, I am uncertain why it is failing on travis. It passes locally.

Save Recipe Workflow

---

core/sagas/inputs.js

The function `updateInputComponentData()` was fixed recently [1] to be
synchronous instead of async, so it is correct now and the eslint
error is gone. Drop the annotation to avoid confusion and regression.
[1] https://github.com/weldr/welder-web/commit/50630524afbc1c03eb06204a44240edceea45498#diff-9e47aee6cedcc9f80cf6432dc6e63aff
----
This is cleanup from #151.

Drop obsolete eslint override

---

public/manifest.json

Cockpit uses menu items which are a functional description
("Networking", "Containers", "Logs", or "Dashboard"), not product names
("Network Manager", "Docker", or "systemd"). Consequently, name the
Cockpit dashboard "Image Builder" instead of "Welder".

Rename Cockpit dashboard title

---

Makefile
test/end-to-end/Dockerfile
test/end-to-end/utils/coverage.js

this leaves a functional /tmp in the container and solves issues
with mktemp (called from xvfb-run), possibly triggered by SELinux

Bind-mount .nyc_output/ to /tmp/.nyc_output inside docker

---

Dockerfile.metadata
Makefile
import-metadata.sh

we want to get rid of the humongous CentOS 7 metadata.db and use
a small file for testing. Here metadata.db isn't really used for
anything and is only a requirement so we can run the api
container.

Import minimal metadata.db instead of downloading it

---

.travis.yml
Makefile
test/end-to-end/entrypoint.sh

1. Run end to end and cockpit tests containers on localhost of host namespace.
2. For cockpit test, run all three containers on host namespace.
3. Remove some lines of sed codes because of two above changes.

Run end to end test on host network namespace, not on its own namespace.

---

components/Modal/PendingChanges.js
components/Toolbar/Toolbar.js
core/actions/recipes.js
core/apiCalls.js
core/constants.js
core/reducers/recipes.js
core/sagas/inputs.js
core/sagas/recipes.js
data/RecipeApi.js
pages/recipe/index.js
pages/recipeEdit/index.js
pages/recipes/index.js

A user should now be able to view a list of pending changes with those from the current session listed in the order they were made (newest first) and the unsaved updates from prior sessions shown separately. The user can discard these pending changes and can undo/redo both local and workspace changes. This PR does not include the discard changes modal, the pending changes modal info tooltip, nor an alert when undoing workspace changes. Also, when loading components from the workspace the only dependencies loaded are the components themselves.

Load Pending Changes from Workspace

---

test/end-to-end/utils/coverage.js

This issue is caused by saving code coverage result file to a
non-exist folder(/tmp/.nay_output).
To fix this issue, two check points were added.
1. The code coverage result file will not be genreated and saved
if code coverage is not enabeled.
2. If there is no /tmp/.nay_output folder in current system, create
one.

Fix timeout issue when running end to end test in local environment.

---

Makefile
utils/cockpituous-release
welder-web.spec

As discussed on the mailing list, I am working on automating welder-web releases with [cockpituous](https://github.com/cockpit-project/cockpituous). This fixes the tarball and spec file to actually get an idea of releases and versions, and provides an initial cockpituous release script.
I tested this on my own welder-web fork on https://github.com/martinpitt/welder-web, and ran:
in my welder-web branch:
git tag -s 0.0.1 -m "$(printf '0.0.1\n\n- test release\n')"
git push --tags martin
in an empty temporary directory:
~/upstream/cockpituous/release/release-runner -r https://github.com/martinpitt/welder-web utils/cockpituous-release
The latter command would be done by a bot from a cockpituous container eventually, but this makes it easy to test locally.
This produced a first release: …

Prepare for automatic releases

---

components/Toolbar/Toolbar.js
pages/recipe/index.js
pages/recipeEdit/index.js
public/custom.css
test/end-to-end/pages/changesPendingSave.js
test/end-to-end/pages/editRecipe.js
test/end-to-end/pages/viewRecipe.js
test/end-to-end/test/test_editRecipe.js
test/end-to-end/test/test_viewRecipe.js

Updates include:
- Remove Create Composition and Export actions from toolbar and move to top of page, next to Save and Discard.
- Remove non-functional non-mvp actions from toolbar.
- Relabel the link that opens the Pending Changes modal.
- Update Save button to also open the Pending Changes modal.
- Set disable state for page-level actions where needed.
Note: Additional changes are needed that were not made in this PR. The label "Save" should change to "Commit" wherever it is used (i.e. page-level actions, toast notifications, Pending Changes modal), but these changes will be made later when other updates to the Pending Changes modal are completed.

 Update layout of page-level actions on Edit Recipe page

---

Makefile

This fixes 'make build-rpm' which wasn't working with a clean install.

Add npm-install to Makefile's all target

---

core/actions/inputs.js
core/reducers/inputs.js
pages/blueprintEdit/index.js

On the editRecipePage, when filtering inputs, one can now clear the filter by clicking the X icon or Clear All Filters link. Also, when navigating away from the editRecipePage, the filter resets. This covers issue #139

Fix clearing input filter on editRecipePage

---

components/Modal/PendingChanges.js
package.json

- Adds patternfly-react to utilize some of the components in the Pending Changes modal, like Alert and Popover.
- Adds popover with additional info about the changes from a previous session.
- Hides the changes from current session if there are only changes from a previous session.

UI refinements in Pending Changes

---

components/ListView/BlueprintListView.js
components/Modal/DeleteBlueprint.js
core/actions/modals.js
core/reducers/modals.js
core/store.js
pages/blueprints/index.js
test/end-to-end/pages/blueprints.js

This PR includes the following changes:
* Changes the text "Archive" to "Delete" for the action that deletes a blueprint
* Includes a Delete Blueprint modal that displays when the user clicks Delete for a blueprint in the list of blueprints. Previously, this action immediately made the api call to delete the recipe. Now this action is associated with the red button on the modal.

Include modal confirmation for Delete Blueprint

---

components/ListView/ComponentTypeIcons.js

This updates the icon that displays for components to be the one that is used in Satellite for packages.

replace icon used for components

---

utils/cockpituous-release

This will automatically upload and build new releases to our COPR
archive.
Blockers:

Add COPR build to cockpituous release script

---

components/ListView/BlueprintContents.js
components/ListView/ComponentDetailsView.js
components/ListView/ComponentInputs.js
components/ListView/ListItemComponents.js
core/actions/blueprintPage.js
core/actions/blueprints.js
core/apiCalls.js
core/reducers/blueprintPage.js
core/reducers/blueprints.js
core/sagas/blueprints.js
core/sagas/inputs.js
core/sagas/modals.js
core/selectors.js
core/store.js
data/BlueprintApi.js
data/MetadataApi.js
data/NotificationsApi.js
pages/blueprint/index.js
pages/blueprintEdit/index.js
test/end-to-end/pages/toastNotif.js
test/end-to-end/pages/viewBlueprint.js
test/end-to-end/test/test_editBlueprint.js

As a developer, there should be minimal duplicate data in the state. For recipes, we currently have components, dependencies, and packages which all contain similar data. This will be simplified to just components and packages. We then filter our selected components and dependencies from the lists of packages and components.

Simplified component state

---

public/manifest.json

Adds the patternfly icon pficon-build to display as the icon in the Cockpit navigation.
An example of the icon can be seen on the [PatternFly icon page](http://www.patternfly.org/styles/icons/)

add image builder icon for Cockpit nav

---

pages/blueprintEdit/index.js
public/custom.css

This update fixes an issue where a large margin displays above the contents of the Edit Blueprint page, as shown in the following image:

fix layout issue with Edit page

---

Makefile

https://github.com/weldr/bdcs-api/pull/74 changes the format of
Haskell API response for /api/status to match the one from
lorax-composer. This requires updating how we grep for things.
NOTE: this needs to be re-tested and merged after the above PR is merged and a new docker image for the haskell API has been built. Will fail before that!

Adjust how we wait for backend API to become available

---

package-lock.json
package.json

The package-lock.json format handles the optional fsevents dependency
better than npm-shrinkwrap.json. The dependency will appear in the
package-lock file, it won't cause a failure on Linux, and it won't be
constantly added and removed depending on which system last ran `npm
install`.

Use package-lock.json instead of npm-shrinkwrap

---

Makefile

Depends on #237.
Adds two targets which are used by Jenkins to schedule RPM builds and do some sanity tests on the resulting RPMs.
ATM we don't do any sanity testing, just build the artifacts.

Test target for cockpit composer

---

components/Pagination/Pagination.js

Under Firefox on Linux the pagination input rendered to tall due
to the element not having the form-control class, like the other
inputs on the page. This fixes that.
Fixes issue #175

Fix style of pagination input under available components

---

.travis.yml
Makefile
test/end-to-end/entrypoint.sh
test/end-to-end/pages/editBlueprint.js
test/end-to-end/wdio.conf.js

1. Remove Welder-web stand-alone UI test.
2. Add domain socket support for Cockpit integrated welder-web.
3. Add domain socket support for end to end test.
4. Fix a page element.
5. Increase wait time to 60 seconds.

Domain socket support in UI testing.

---

components/ListView/BlueprintContents.js
components/ListView/BlueprintListView.js
components/Loading/Loading.js
components/Toolbar/BlueprintsToolbar.js
core/actions/blueprints.js
core/reducers/blueprints.js
core/sagas/blueprints.js
core/selectors.js
core/store.js
pages/blueprint/index.js
pages/blueprintEdit/index.js
pages/blueprints/index.js
test/end-to-end/pages/blueprints.js
test/unit/index.norecipes.spec.js

The updates included in this PR:
- Refactor the state for `blueprints` to include:
- fetchingBlueprints to indicate when blueprints are being fetched, so that we can display a Loading message on the Blueprints page while this is happening (closes #258)
- errorState for fetching blueprints, so that we can display an error message on the Blueprints page
- errorState for fetching blueprint contents, so that we can display an error message on the Blueprint page > Selected Components tab or Edit Blueprint page
- Display a loading message when fetching blueprint contents
- Update loading component so that it doesn't display immediately
- On Blueprints page, disable actions Create Image and Export when a blueprint has no contents (closes #255)
- On Blueprints page, disable Create Blueprint …

Blueprints page UI refinements

---

core/apiCalls.js
core/utils.js
data/BlueprintApi.js
data/MetadataApi.js
pages/blueprints/index.js

Propagate API errors, so that the UI doesn't show an infinite spinner when an error occurs. This was most visible when logging in with a user that's not root or in the `weldr` group.
See individual commits for details.
Fixes #293

Propagate api errors

---

main.js
package-lock.json
package.json

It's not used anywhere. Also, it is throwing a js error about bootstrap
not being loaded yet.

package.json: Remove bootstrap-select

---

core/utils.js

Update of @stefwalter's patch in #246. Always require sudo, as discussed on that pull request.

core: Use escalated privileges to access Lorax API

---

utils/cockpituous-release

cockpituous' release-source script recently learned how to build release
tarballs for plain Makefile projects (like welder-web) that use
`make dist-gzip`. So drop our own function for it.

cockpituous-release: Use upstream release-source

---

Dockerfile.buildrpm
Dockerfile.cockpit

we don't really consume the src.rpm package for the moment but
at least build it so we can see if the build breaks.

Build srpm together with rpm

---

Dockerfile.cockpit

The rpm package should be welder-web*.noarch.rpm, not welder-web*.x86_64.rpm

Fix PR#309 imported issue.

---

components/ListView/ListItemImages.js
core/sagas/composes.js
pages/blueprint/index.js

Since images can become quite large, we don't want to load them into memory with `cockpit.http()`. Instead, use cockpit's special `cockpit/channel/` url to create a url which is backed by a cockpit http-stream2 channel.
Blocked on

Download images

---

core/apiCalls.js

When creating an image the console would log a startComposeError and our start composer saga wasn't getting a response, I fixed this by adding a missing return statement

Fixed bug where startComposeApi would not return start compose response

---

data/BlueprintApi.js
pages/blueprintEdit/index.js

Removed the updateBlueprint function since it provided no functionality not being handled by redux and was adding/removing components for a blueprint's entire history.

Fix blueprint packages getting added to history

---

components/ListView/ListItemImages.js
public/custom.css

- Modifies css to accommodate extra `<span>` added for translated strings so that date and type values will wrap on wider screens.
- Adds `div.list-pf-actions` for list items that don't have actions since this div is required for flex layout and alignment across all the list items.
**Screencaps of expected layout
window width < 992px**
**window width > 992px**

Adjust Images list layout to improve alignment

---

Makefile

So that they will always get updated with the correct version-release
even if they already exist.

Add the .spec files to .PHONY

---

components/Modal/PendingChanges.js
public/custom.css

This PR updates the Pending Changes dialog so that the strings can be translated.

Make strings translatable in Pending Changes dialog

---

components/ListView/ListItemImages.js

After the API updates to provide 3 timestamps, the property key for the Date Created value from the API no longer matched the property key expected in the UI. This updates the UI to use the new property key from the API so that the date displays as shown below.

Fix issue with displaying Date Created in list of Images

---

components/ListView/BlueprintListView.js
components/Modal/CreateBlueprint.js
components/Modal/CreateImage.js
core/actions/composes.js
core/actions/modals.js
core/apiCalls.js
core/reducers/composes.js
core/reducers/modals.js
core/sagas/composes.js
core/store.js
data/BlueprintApi.js
pages/blueprint/index.js
pages/blueprintEdit/index.js
pages/blueprints/index.js
test/end-to-end/pages/viewBlueprint.js
test/unit/create.image.spec.js

These updates will display a warning message in the modal dialog to the user for the following cases:
- The blueprint is empty
- The blueprint has unsaved changes
- This case required a small change to the data returned by fetchBlueprintInfoApi to also include the `changed` value. On the blueprints page, this is the only way we know if there are unsaved changes in the workspace, without fetching the blueprint contents.
_Deleted the example of the second case. An updated example is included [below](https://github.com/weldr/welder-web/pull/330#issuecomment-416083737)_

Display warning messages to the user in Create Image modal

---

components/Modal/CreateImage.js
core/actions/blueprints.js
core/apiCalls.js
core/reducers/blueprints.js
core/sagas/blueprints.js
data/BlueprintApi.js
pages/blueprintEdit/index.js

This closes #337
The issue with saving changes made on the Edit Blueprint page was mostly addressed in #330. But these changes now only pass in data needed to post blueprint updates, and not _everything_ like before this PR. 
However, when editing the description on the blueprint page, the groups and customizations weren't being preserved, and the updated version number wasn't getting fetched and updated in the store. Edit Description action will now pass blueprint groups and customizations when posting the updated description and also reloads the updated version number.
Since the user could make changes to the blueprint and then edit the description before saving those changes, I decided to handle this use case by doing the following:
1.  When setting the updated description, the oldest …

pass blueprint data that's expected on save

---

core/selectors.js

This fixes a bug with how the list of Selected Components is created.
The list of Selected Components is created by filtering out the selected items from the list of everything (returned from the api as "dependencies"). But currently, only the selected items that are packages are being filtered out of this list. Instead, packages and modules that are selected for the blueprint should display in the list of Selected Components.

Display modules in list of selected components

---

components/Toolbar/BlueprintToolbar.js
core/actions/blueprints.js
core/apiCalls.js
core/constants.js
core/sagas/blueprints.js
data/BlueprintApi.js
pages/blueprintEdit/index.js

This closes #327.
These updates will delete a workspace if one exists when the user selects an action to discard the changes in a workspace, using either the Discard Changes button or the Undo button.
After the workspace is deleted, an additional api call is made to get the blueprint so that we can load the correct blueprint contents in the UI.
A couple of things to note:
- I'd like for the user to be able to hit Redo to get changes back that were discarded. I think this could be a simple change, but will open a separate PR for that.
- While working on this, I noticed that there are other places where we don't handle components that are stored in the blueprint as 'modules' very well, like removing components that are modules, or reloading the blueprint when changes are made. I will open a …

Update Discard Changes to delete workspace

---

test/check-application

It's caused by return value. The run_webdriver_tests() has to return ture or false in this case. Adding return value in run_webdriver_tests() fixed this issue.

Find the root cause of exiting with none 0 code and fix it.

---

test/selenium_start.sh

https://github.com/cockpit-project/cockpit/pull/10191 will update
Cockpit's selenium image to have (only) the -debug variants of the
firefox and chromium containers. Temporarily support both, so that we
can run welder-web tests with both the current and that new image, and
never have to break tests.
This can be simplified to only using the -debug variants after landing
the above PR.

Temporarily support selenium images with and without -debug variants

---

.gitignore
Makefile
test/check-application
test/end-to-end/wdio.conf.js

@martinpitt, could you please add another test in cockpit CI to run test on chrome with code coverage enabled? Thanks.
The test needs two environment variables in cockpit CI container.
1. CODECOV=true
2. CODECOV_TOKEN=<token>
Could you please add two environment variables? Thanks.

Compile with code coverage enabled, collect coverage result and upload result to codecov.

---

components/Modal/CreateImage.js
core/apiCalls.js
test/end-to-end/pages/createImage.js
test/end-to-end/specs/test_viewBlueprint.js
test/end-to-end/wdio.conf.js

Closes #371 
Adds user-friendly labels to display in the Create Image dialog, as shown below. 
Please note - Labels are provided for new images types added in https://github.com/weldr/lorax/pull/475, but are not shown in the example above since I am currently only running the latest version of lorax-composer that is available to install.

Creates user-friendly labels to display for image types

---

Makefile
test/check-application

We can use VNC to watch the end to end test process in real browser (firefox and chrome).
@martinpitt, could you please forward port 5901 and 5902 in selenium VM? Thanks.

Add selenium debug support.

---

components/Modal/PendingChanges.js
core/actions/blueprints.js
core/apiCalls.js
core/reducers/blueprints.js
core/sagas/blueprints.js

Previously, the UI only handled packages during add/remove
and ignored modules, which resulted in odd behavior, like
modules disappearing from the UI during add, or not being
able to remove modules from a blueprint. These updates
add support for blueprints that have components listed as
modules in the blueprint contents.

Add support for Modules during Add/Remove

---

components/Modal/CreateImage.js
test/unit/create.image.spec.js

Instead of defaulting to the first image type in the select menu, the select menu displays "Select one" by default. This is a disabled option which means it can't be selected in the menu.
This menu is also indicated as required to prompt the user to make a selection, and the submit button is disabled until an option is selected.
Example of modal when it first displays:
Example of select menu when open:
Closes #374

Updates Create Image modal to not have a default image type

---

Makefile

bots/ is an actual directory and thus an intended make target. It should
*not* be checked out again if it already exists, as that breaks testing
a bots/ from a cockpit PR against welder-web.

Makefile: bots is not a phony target

---

test/vm.install

Cockpit's rhel-7-6 image will soon pre-install node, as this is brittle
and time consuming when running for each test. As this code is not
reentrant, check if node is already installed before installing it.
With that we can update the cockpit image without breaking welder-web in
between. After that landed, this can go completely.

test: Only install node if it isn't already available

---

test/end-to-end/pages/deleteBlueprint.js

According to failed case screen shot, the timeout should be at deleting blueprint.

Wait for delete menu action visible before click it.

---

components/Modal/CreateImage.js
test/end-to-end/pages/createImage.js
test/end-to-end/specs/test_blueprints.js
test/end-to-end/specs/test_createImage.js
test/end-to-end/specs/test_editBlueprint.js

Composer creates images in the architecture of the system it
is running on, and based on the source of the RPMs it has
access to (at least for the forseeable future).
This means this field in the Create Image dialog doesn't
do anything. And seems to be filled with placeholder text.

Remove inert 'Architecture' field in 'Create Image' dialog

---

Makefile
test/run

https://github.com/cockpit-project/cockpit/pull/10194 introduces test
scenarios in Cockpit CI, and defines two scenarios "chrome" and
"firefox". These directly map to the Makefile's `$BROWSER` variable.

test: Support Cockpit test scenario (actually enable testing on Chrome)

---

Makefile

This will also build the spec file as part of `make`, which unbreaks
automatic cockpituous releases.

Include spec into release tarball

---

test/check-application
test/end-to-end/package.json
test/vm.install

1. Update wdio-mocha-framework to 0.6.4 to support nodejs 10.
2. Update grep regxp to support lorax-composer response on Fedora 29.

Two updates to support nodejs 10 and Fedora 29.

---

public/custom.css

The usage of the -ms-grid property causes issues on Edge.
The ms-grid property was used to support IE, but since we decided
to not support IE, we can now use the standard grid css properties.
Edge has full support for grid properties since version 16.
See https://caniuse.com/#feat=css-grid
Fixes issue #394

Remove deprecated -ms-grid properties

---

core/apiCalls.js

OpenStack didn't have a proper name in the dropdown, but took it
directly from the API. This commit adds an entry that uses the
corrent capitalization of the product.
Fixes issue #399

Capitalize OpenStack corrently in the image create dialog.

---

.tasks

This currently wreaks havoc and creates a never-ending stream of
po-refresh tasks which get immediately closed again.

tasks: Temporarily disable po-trigger

---

.tasks

This reverts commit 91e2b6c76a2a2b09e55a8f82a8c4543bf6e9a3fd.
This got fixed in https://github.com/cockpit-project/cockpit/pull/10666

Revert "tasks: Temporarily disable po-trigger"

---

package.json

patternfly 3.59.0 requires bootstrap 3.4.0 which resolves a cross-site scripting vulnerability:
https://snyk.io/vuln/npm:bootstrap:20160627
Please also consider using https://snyk.io for security monitoring and https://greenkeeper.io/ to automatically open pull requests that update npm dependencies.

package.json: Update patternfly dependency for XSS vulnerability

---

test/end-to-end/components/AvailableComponents.component.js
test/end-to-end/specs/editBlueprint1.test.js
test/end-to-end/specs/editBlueprint2.test.js

Issues only impact tests on rhel-7-6 because composer UI on rhel-7-6 is slower than on RHEL-8 and Fedora. After some changes happened and before next action started, the page element has to be "wait for exist".
Issue 1: To wait until package filter done, the filter label content should be checked, not just filter label element.
Issue 2: To add or remove package from blueprint, wait until the + or - button exists.

Fix two issues imported by PR #469

---

Makefile
README.md

1. Fix a typo and update directory layout description in README.me.
2. Remove "npm run translations:po2json" in Makefile because it has been included in "npm run build".

Two small fixes

---

test/end-to-end/wdio.conf.js

Because the test code in "after" hook cannot get covered if we collect coverage result in "afterTest" hook.

Move coverage collector to afterSuite hook from afterTest hook.

---

Makefile

`make devel-install` will make a link in ~/.local/share/cockpit to the
current checkout.
Taken from cockpit-project/starter-kit.

Makefile: Add devel-install target

---

Makefile

1.$(PACKAGE_NAME) in this case is cockpit-composer, not welder. I know it's wired, but we need keep welder for now.
2. There's no $(WEBPACK_TEST) in this project.
3. devel-install should be in .PHONY

Fix devel-install target in Makefile.

---

components/ListView/ComponentDetailsView.js
components/ListView/ComponentInputs.js
core/sagas/inputs.js
pages/blueprintEdit/index.js

Originally, we had discussed adding the easiest fix for this issue, which was assumed to be always saving the version as "*". But after considering the following:
- Updates in #500 included the ability to select one out of a list of all available versions that are returned  
- The effort involved in removing all of that seemed more complicated than just adding on the ability to select a wildcard version
- In the cli, the user can specify a specific version or any variation of a wildcard version (e.g. 1.2.3, 1.2.*, 1.*, *)
It seemed like the easiest path was to just update the list of available versions to include wildcard variations of the versions.
Updates included in this PR:
- By default, the wildcard version "*" is selected/added to a blueprint. 
- Previously, clicking the + icon in …

Enables user to specify wildcard version value

---

Dockerfile.buildrpm
cockpit-composer.spec.in
io.weldr.cockpit-composer.metainfo.xml

From Fedora inclusion review bug https://bugzilla.redhat.com/show_bug.cgi?id=1659556

Packaging fixes

---

Makefile

Packaging test folder makes test easy on dist-git.

Package test folder to tar.gz.

---

package.json

Two reasons:
1. It is not used any more.
2. It caused severity vulnerability due to lower version.

Remove browser-sync in devDependencies.

---

test/check-application

It'll be easy to track tested package version.
Two steps:
1. Save version into /tmp/composer.covered.
2. Upload composer.covered into result server.

Save cockpit and lorax-composer package version information.

---

.eslintignore
.gitignore
package.json
test/end-to-end/specs/api.test.js
test/end-to-end/wdio.conf.js

1. Update .gitignore and add .eslintignore 
- Make git ignore composer.covered.
- Do not run eslint on all node_modules and wdio_report. Eslint ignores node_modules folder in root folder by default, but does not ignore /test/end-to-end/node_modules. There's a app.js inside wdio_report. Eslint should ignore that.
2.  Add API response time and sanity functional test.
- Check API response time to find API issue ASAP.
- Reload browser before test suite starts to clear browser session.
- Add "cockpit" into eslintConfig global to avoid eslint error.

 Add API response time and sanity functional test.

---

package.json

1. Remove hightlight.js because we do not need it any more and it has a bug which caused installation issue.
2. Update bootstrap to 3.4.1 to fix CVE-2019-8331.

Fix two dependencies issue

---

components/Form/TextInlineEdit.js
core/actions/blueprintPage.js
core/actions/blueprints.js
core/apiCalls.js
core/reducers/blueprintPage.js
core/reducers/blueprints.js
core/sagas/blueprints.js
core/store.js
data/BlueprintApi.js
pages/blueprint/index.js
public/custom.css
test/end-to-end/pages/ViewBlueprint.page.js
test/end-to-end/specs/viewBlueprint.test.js

Adds ability to edit the hostname defined for a blueprint, which is similar to the ability to edit the blueprint description.
Also refactors the edit blueprint description functionality:
- Uses inline edit css available from PF3
- Moves input value out of the redux store to the component state to avoid lagging during typing
- refactors the function to cause a version bump when description is updated (previously, version would not change)
- Improves the keyboard interaction of the inline edit functionality (e.g. places focus on the input when it becomes visible, enables Escape key to exit out of inline edit)

Hostname config

---

.tasks

We don't need to file or check for these issues on every iteration
through the .tasks script. These will count as "work done" and thus skip
the sleep (even though the "work" lasts only a split-second), and are
prone to creating duplicates.
Similar to https://github.com/cockpit-project/cockpit/commit/af2e934a

tasks: Minimize races filing issues for bots [no-test]

---

cockpit-composer.spec.in

Spotted in https://bugzilla.redhat.com/show_bug.cgi?id=1659556

spec: Keep original upstream time stamps

---

cockpit-composer.spec.in

Because of https://bugzilla.redhat.com/show_bug.cgi?id=1659556#c19
Taken from README

spec: Update description to be more verbose

---

test/end-to-end/package.json
test/end-to-end/specs/editBlueprint2.test.js
test/end-to-end/wdio.conf.js

1. Add xunit format report output to support tier-1 result dashboard
2. Change package name from bash to tmux. Package filter result for bash package has lots of matches in some scenarios. It's very hard for test to pick this package. Changing to tmux makes things easy.

Two updates for Tier-1 test

---

utils/cockpituous-release

cockpit-composer is in rawhide now, so upload new releases automatically
to there.

cockpituous: Release to Fedora Rawhide

---

core/sagas/blueprints.js

When the api call constants.get_blueprints_deps returns a list of dependencies, if a package has more than one arch, then each arch is a separate item in the array of dependencies. Since the list item key is based on the name, this results in issues when rendering the list of contents as they are updated due to the key not being unique.
This update removes duplicates in the list of selected components and dependencies.

Addresses issue with duplicate keys when multiple arches

---

components/Form/Password.js
components/Modal/UserAccount.js
core/actions/blueprints.js
core/actions/modals.js
core/reducers/blueprints.js
core/reducers/modals.js
core/sagas/blueprints.js
core/store.js
pages/blueprint/index.js
public/custom.css

- User account creation allows for defining name, description, password, ssh key and also enabling the user to be a server admin (i.e. groups=["wheel"]).
- When an ssh key is provided, no validation occurs. When the account is listed on the Details page, if the key includes an email address, that is the only part of the key that displays in the table.
- When a password is provided, an encrypted password is stored in the blueprint. When the account is listed on the Details page, only a checkmark icon displays to indicate that a password is set. When editing a user account, the password can be deleted or a new password can be set.
- User accounts can also be updated or removed.
- User accounts that are created for a blueprint are listed on the Details tab of a blueprint.
- Text strings and …

Include ability to add a user to the blueprint

---

components/Modal/PendingChanges.js

Without this fix I get the following warning in console:
'Failed prop type: The prop `id` is required to make `Popover`
accessible for users of assistive technologies such as screen readers.'

Add id to Popover in PendingChanges component in order to fix console warning

---

core/sagas/blueprints.js
core/sagas/modals.js

Unlike the other pages, the Export modal on the Blueprints page requires an api call to fetch the contents of the modal. This was broken in #500 when the api calls were refactored. This update
moves the functionality from the modals saga to the blueprints saga to reuse functions that handle flattening the list of components after the api call.

fixes issue with fetching contents for Export modal

---

test/end-to-end/specs/api.test.js
test/end-to-end/wdio.conf.js

1. Make all timeout timers in wdio.conf.js configurable by ENV.
2. Not run API test until the blueprints page is fully loaded. That just waits for cockpit available.

Two updates for ARM64 testing scenario.

---

test/end-to-end/specs/api.test.js

On the loaded OSCI infrastructure, which uses nested VMs, the test often
takes much longer; times up to 6.5 seconds have been observed. Bump the
timeout to 10 seconds so that we don't have to fight numerous failures.

test: Bump API sanity test timeout

---

core/sagas/blueprints.js
core/sagas/composes.js
core/sagas/inputs.js

While testing Composer on RHEL 8 Betas I've noticed various
failures in the javascript console, but the actual error content
was hidden. This impedes support, especially of production systems.
I've added full error output to go to the javascript console
in each of these cases.

core: Don't hide errors in sagas

---

test/end-to-end/specs/api.test.js
test/end-to-end/specs/blueprints.test.js
test/end-to-end/utils/commands.js

1. Add blueprint export test on blueprints page.
2. Move apiFetchTest() function to utils/commands.js because it will be re-used by api.test.js and blueprints.test.js

test: add Export test on bluepirnts page to address PR#604

---

test/end-to-end/specs/createImage.test.js

It's rhel-8-1 ONLY. Two new types are not supported on Fedora.
This's a quick fix. Case will be updated when UI has update according to new types.

test: update test case to support two more image types.

---

components/ListView/BlueprintListView.js
components/Modal/CreateBlueprint.js
components/Modal/CreateImage.js
components/Toolbar/BlueprintsToolbar.js
core/actions/composes.js
core/actions/modals.js
core/apiCalls.js
core/reducers/composes.js
core/reducers/modals.js
core/sagas/composes.js
core/sagas/modals.js
core/store.js
package.json
pages/blueprint/index.js
pages/blueprintEdit/index.js
pages/blueprints/index.js
test/end-to-end/pages/createBlueprint.page.js
test/end-to-end/specs/createBlueprint.test.js

This commit introduces the following changes:
* The dialog uses now Modal component from patternfly-react
* All properties that can be derived from others were removed from props
* The Button with the Modal for Create image belong now to the same
component. This removes the need for handlers getting passed all
around
* Stop using jquery for handling the modal state
* Remove from global state all properties that are Modal state specific
* The list of images types was moved out from the modals object in the
global state, since it's not really related to the that

Refactor CreateImage && CreateBlueprint modal dialogs

---

components/ListView/BlueprintListView.js
components/Modal/DeleteBlueprint.js
core/actions/modals.js
core/reducers/modals.js
pages/blueprints/index.js
test/end-to-end/pages/deleteBlueprint.page.js

The following changes where also introduced:
* The link that triggers the dialog was moved to the same component as
the modal
* All delete blueprint modal related fields where removed from the redux
store, and similarly all related saga actions
* Stop using jquery to show/hide the modal; instead use event handlers on
the buttons

WIP: Refactor DeleteBlueprint modal dialog to use Modal from PF react

---

Makefile

New version of po-refresh bot also needs `clean-po` command.
This command is used for dropping languages that do not have sufficient
translation coverage anymore - currently all languages that have at least
one translated word in welder-web are pulled. So non languages will drop
anyway, but if once introduced minimal translations rule then languages
could be dropped (but seems that zanata-js does not support min-translation)
See also: https://github.com/cockpit-project/cockpit/pull/11638

po: Add cleanup commands

---

package.json

Fix [CVE-2019-11358](https://github.com/weldr/welder-web/network/alert/package.json/jquery/open).

Update jquery dependence to fix CVE-2019-11358

---

components/Modal/CreateImage.js
core/sagas/blueprints.js

This PR addresses a couple of issues related to how changes that are saved to the workspace are handled. 
- The Create Image modal should display a warning if changes are saved to the workspace. 
- Make changes to a blueprint, then click Create Image. The modal will display a warning about unsaved changes.
- Dismiss the modal and reload the page. Then open the Create Image modal again. The warning no longer displays.
- These updates will now display that warning message for changes from the workspace.
- The example blueprints have some packages defined as "Modules" which results in issues with how these are listed in the Pending Changes modal if they are removed or updated without immediately committing them (i.e. if they are retrieved from the workspace in a later session).
- Make …

Resolve issues with changes saved to the workspace

---

components/Modal/UserAccount.js

Address issue [613](https://github.com/weldr/welder-web/issues/631)
Use python to generate sha512 hashed password in all platforms

Fix "passwd in rhel 7 does not support sha512" issue

---

.travis.yml
Makefile
package.json

3.0.2 is broken for us because of
https://github.com/formatjs/babel-plugin-react-intl/pull/165
`formatMessafe()` calls are not recognized as coming from injectIntl().

Pin babel-plugin-react-intl to 3.0.1

---

test/end-to-end/pages/blueprints.page.js
test/end-to-end/wdio.conf.js
test/vm.install

1. Start lorax-composer to initial package index at vm setup stage, but not "enable" it to make it inactive when test running. Tests expect the service to not run, it checks the "start service" button
2. Reset all timeout value which changed on PR#639 because test does not need that much time to wait package index initialization

test:  Initial lorax-composer package index at vm setup stage instead of at test phrase

---

test/end-to-end/wdio.conf.js

The page element waiting timeout is 2 min and an error log will be printed in console when element does not appear in timeout. Test should have a longer timeout to have element error log printed

test: Add mocha timeout from 2 min to 5 min

---

test/end-to-end/specs/viewBlueprint.test.js

The export copy and paste case sometimes failed on Edge browser, add one more step before paste exported content

test: Click input box before Ctrl-V to make case more stable

---

pages/blueprint/index.js

Currently, a compose will fail if any of the defined users have newline characters in their SSH key, which is especially unfortunate because SSH public key files like `~/.ssh/id_rsa.pub` typically end with a newline. This patch trims whitespace from both ends of the key so a user can fill out the field by pasting the contents
of an SSH public key file.
See https://github.com/weldr/lorax/pull/752.

Trim whitespace from SSH keys before saving

---

utils/cockpituous-release

Use release-srpm's `-V` option [1] so that the generated srpm will get a
proper changelog and Release "1" instead of "2".
[1] https://github.com/cockpit-project/cockpituous/commit/abb2bdb5

cockpituous: Fix srpm Release:

---

test/end-to-end/specs/viewBlueprint.test.js
test/end-to-end/wdio.conf.js

1. The maxInstances in different capability will inherit from up level if it is not configured.
2. Sometimes the Control-v does not work on Edge browser, and there's not a better way to check the copied content. Checking stage in the test will be passed on Edge but still keep clicking copy button part

test: Remove maxInstances from capabilities in wdio.conf.js and skip copied content checking on Edge

---

main.js

If `cockpit.language` is undefined (which can happen in practice), just
default to English instead of crashing on calling
`undefined.includes()`.

Fix crash if no language is set

---

components/ListView/BlueprintContents.js

The message that was being passed to the EmptyState for the blueprint components on the Edit Blueprint page was accidentally changed in a previous PR. This PR reverts that change.

updates prop being passed to EmptyState contents

---

components/ListView/BlueprintContents.js

Fixes build failure:
```
components/ListView/BlueprintContents.js
59:28  error  'errorState.msg' is missing in props validation  react/prop-types
```
This was previously erroneously changed the other way around in commit
56f688dde48dc6, which got reverted in commit 5b38c5efbf.

Fix errorState.msg propType

---

components/ListView/SourcesListItem.js
components/Modal/ManageSources.js
public/custom.css

This fixes issue #646
After deleting a source the options to edit  will be replaced by a
spinner and text saying "Deleting source".

Add notification for source repo deletion

---

components/ListView/BlueprintListView.js
components/Modal/CreateImage.js
core/actions/composes.js
core/sagas/composes.js
pages/blueprint/index.js
pages/blueprintEdit/index.js
pages/blueprints/index.js

This fixes issue #689. 
The fetchComposeTypes saga was blocking other compose sagas from running
on a page refresh. Instead of default calling fetchComposeTypes on the
application loading this saga is now called by a dispatched action.

Fix images not loading on refresh

---

components/Modal/CreateBlueprint.js
test/end-to-end/specs/createBlueprint.test.js

Fixes #317
A user attempting to create a blueprint with spaces or other invalid
charaters in the name will be notified about the invalid character and
prevented from creating the blueprint.

Add additional blueprint name validation

---

package.json
public/custom.css
public/index.ejs
webpack.config.js

Cockpit's patternfly.css already sets the correct font paths, and does
not have any other modifications right now (Cockpit specific
modifications live in the separate cockpit.min.css).
This will automatically pick up future adjustments to Cockpit PatternFly
styling, such as in https://github.com/cockpit-project/cockpit/pull/11987,
nd thus ensure that all Cockpit pages will have a consistent look and
feel.
This also avoids shipping the PatternFly css and fonts and thus makes
the package much smaller.

Use cockpit's PatternFly CSS

---

io.weldr.cockpit-composer.metainfo.xml

Cockpit renamed its ID to "org.cockpit_project.cockpit" to conform to
the AppStream spec [1]. Follow suit and also fix our own ID to not
contain hyphens.
[1] https://github.com/cockpit-project/cockpit/commit/4a9ffe669c

Fix AppStream ID

---

components/ListView/ListItemComponents.js

Homepage is always returned as a single string from the API.

Fix wrong PropType for homepage

---

test/check-application

See https://github.com/cockpit-project/cockpit/pull/12569
Mind you, this will fail now, since `VirtNetwork` does not have `image` argument in constructor.
However without this change https://github.com/cockpit-project/cockpit/pull/12569 fails.
There is no way how to test PR in external project from PR in Cockpit :)
It would be awesome if @henrywang could test it together with https://github.com/cockpit-project/cockpit/pull/12569.
When this is approved I would prefer to first merge https://github.com/cockpit-project/cockpit/pull/12569 and then this PR (since if this is first merged nothing can be tested here, but on cockpit it blocks much less things)

Use virtio-net instead of rtl8139 network cards for test

---

test/check-application

Our internal CI now has npmjs.com access firewalled off, and sets an
internal NPM registry mirror. Make sure to use that in the nested VM as
well.

test: Use same NPM registry in VM as on the test host

---

babel.config.js
main.js
package.json
webpack.config.js

According to https://babeljs.io/docs/en/next/babel-polyfill, @babel/polyfill has been deprecated in Babel 7.4.0.

Remove @babel/polyfill, use core-js and regenerator-runtime instead

---

Makefile
test/check-application

Move the default RAM size of the composer VM from the Makefile to
check-application, so that it applies also when running the latter
directly.
Bump memory size of the composer and the windows-10 VMs to avoid
running out of resources, causing "Couldn't connect to selenium server"
test failures.

test: Bump RAM of test VMs

---

components/Layout/Layout.js
components/ListView/BlueprintContents.js
components/ListView/DependencyListView.js
components/ListView/ListItemComponents.js
components/Modal/CreateImage.js
components/Modal/EditDescription.js
components/Modal/PendingChanges.js
components/Notifications/Notification.js
components/Pagination/Pagination.js
components/Toolbar/FilterInput.js
pages/blueprint/index.js
pages/blueprintEdit/index.js
pages/blueprints/index.js

In React 17 componentWillMount, componentWillUpdate, and componentWillReceieveProps are deprecated. The functionality triggered by these hooks has been updated and moved to other methods.

Update deprecated lifecycle methods

---

test/vm.install

The `yum` has been removed since Fedora 31.
https://fedoraproject.org/wiki/Releases/31/ChangeSet#Retire_YUM_3
Solution is use `dnf` in Fedora and keep `yum` in RHEL
`which` is non-standard. Use builtin `command -v` instead

Use dnf instead of yum in Fedora to support Fedora 31 and use command -v instead of which

---

test/vm.install

The fibers (one of dependence of wdio_sync) does not work with nodejs v12 and Fedora 31 install nodejs v12 by default. Installing nodejs v10 works around this issue

Install nodejs v10 in Fedora 31, not v12 by default

---

components/ListView/ListItemImages.js
test/end-to-end/pages/ViewBlueprint.page.js

Fix failed case issue:
```
1) View Blueprint Page image type should be tar:
expected '' to equal 'tar'
```
The failed case is because the openssh-server dependencies on RHEL 7.8
have tar included. The selector 'strong=tar' will have two elements
matched, and the first matched element is the dependence one, not the
image type. But the tar is not one of dependencies of openssh-server on
Fedora or RHEL 8. So this issue cannot be found on those two test
scenarios.

test: Fix "View Blueprint Page image type should be tar" case failed on RHEL-7-8

---

README.md

The README instructed users to symlink ./public into ~/.local/share/cockpit/composer. This does not properly install cockpit-composer. In order to install cockpit-composer into cockpit a user must first build the dist and then symlink ./public/dist into ~/.local/share/cockpit/composer.

readme: update instructions on installing into cockpit

---

core/composer.js

New labels are added for alibaba, google, and hyper-v options.
The label for openstack is updated to match what displays in documentation.
This commit addresses issues noted in
https://bugzilla.redhat.com/show_bug.cgi?id=1769154

Adds new labels and updates one label for image output options

---

components/ListView/BlueprintContents.js
components/ListView/ComponentDetailsView.js
components/ListView/ComponentsDataListItem.js
components/ListView/LabelWithBadge.js
core/reducers/blueprints.js
core/sagas/blueprints.js
pages/blueprintEdit/index.js

Before this update, if a blueprint had a package with a version that resulted in a depsolve failure, then an error message would display in the Edit page, and the only workaround for fixing the error is by editing the TOML file through the cli.
This update still displays the error message, but also includes the list of selected components so that the user can find the component that is mentioned in the error and resolve the issue by either removing the component or selecting a different version.
~Still to be included is the last statement in issue #718 (i.e. preventing the user from creating an image when an error exists).~ Going to defer this to a future PR.
Some ways to test this:
1. Add the package "soletta" to a blueprint. In this case, dependencies required by soletta are missing and …

Allow user to fix depsolve errors on Edit page

---

test/check-application

The old "selenium" image got deprecated.
See https://github.com/cockpit-project/bots/pull/281 for details.

Use selenium containers on services image

---

components/ListView/ImagesDataList.js
components/ListView/ListItemImages.js
components/ListView/ListItemUploads.js
components/Logs/Logs.js
pages/blueprint/index.js
public/custom.css
test/end-to-end/pages/ViewBlueprint.page.js
test/end-to-end/specs/imageBuilding.test.js

This is a duplicate of #846 except that it is based on master instead of #767.
- Updates text strings based on [latest design](https://docs.google.com/presentation/d/1LCvefUG_a3o4M2Cf4xbhtNHEeyJJ2uzfQpmycKEBJHY/edit?usp=sharing) and moves most of them to the beginning of the file
- Adds image size to the image list item
- Migrates list of images to PF4 data list component and makes layout updates based on [latest design](https://docs.google.com/presentation/d/1LCvefUG_a3o4M2Cf4xbhtNHEeyJJ2uzfQpmycKEBJHY/edit?usp=sharing)
- Moves Logs contents to a separate component for future use with Uploads list

Migrates Images list view to the PF4 data list

---

test/end-to-end/package.json
test/end-to-end/wdio.conf.js

Timeline report aggregates all the typical information you will need into one report. Run tests and have a nice timeline of events you can look back at to further verify everything looks ok.
Report example:
[Edge](https://209.132.184.41:8493/logs/pull-848-20191213-065656-c6b2d24a-weldr-cockpit-composer--fedora-31-edge/wdio_report/timeline-reporter.html)
[Firefox](https://209.132.184.41:8493/logs/pull-848-20191213-065656-c6b2d24a-weldr-cockpit-composer--rhel-7-8-firefox/wdio_report/timeline-reporter.html)
[Chrome](https://209.132.184.41:8493/logs/pull-848-20191213-065656-c6b2d24a-weldr-cockpit-composer--rhel-8-1-chrome/wdio_report/timeline-reporter.html)

test: Add timeline test report

---

Makefile

Fedora-29 does not exist anymore.

Makefile: Bump default TEST_OS to Fedora-31

---

utils/cockpituous-release

As part of the move to using osbuild-composer instead of lorax, we should only release on fedora-31 since the other distros will fail to install osbuild-composer. This PR is required for #868

cockpituous: remove releases except for fedora-31

---

test/vm.install

Some tests take too long (like when image is being built) and cockpit
session times out.
Also it is very likely that selenium tests do not bump the timeout with
their actions.

tests: Disable session timeout

---

utils/cockpituous-release

It branched off on Feb 11:
https://fedorapeople.org/groups/schedule/f-32/f-32-key-tasks.html

cockpituous: Release to Fedora 32

---

test/vm.install

In Fedora, golang-github-osbuild-composer Provides: lorax-composer, but
does not currently fully replace it (e. g. it doesn't provide
lorax-composer.service). Also, we want to be explicit about which
backend we test against. So always explicitly install lorax-composer for
now.
In the future, we can add another scenario that tests against osbuild,
but that needs slightly different setup.

test: Always explicitly install lorax-composer

---

test/check-application
test/end-to-end/wdio.conf.js

1. Always download junit report because it's required by gating
2. Download timeline report for test failed only

test: Adjust report download strategy

---

.travis.yml

There's a deploy job to push to zanata in Travis. It caused Travis failed when when PR is merged into master. Since we do not use zanata any more, zanata setting should be removed.
Failed deploy job can be found from https://travis-ci.org/github/weldr/cockpit-composer/jobs/667298469?utm_medium=notification&utm_source=github_status

Remove zanata configuration from .travis.yml

---

Makefile
README.md
cockpit-composer.spec.in
test/end-to-end/HACKING.md
test/end-to-end/specs/blueprints.test.js
test/end-to-end/specs/createImage.test.js
utils/cockpituous-release

All references to weldr/cockpit-composer are changed to osbuild/cockpit-composer since the url will change when cockpit-composer is migrated from weldr to the osbuild org.
This PR should not be merged until cockpit-composer and cockpit-composer-weblate have been moved to the osbuild organization.

prepare to migrate to osbuild organization

---

components/ListView/ListItemImages.js

osbuild-composer does not support stopping an image build. Therefore, the stop option has been removed from pending or building images. Thestop modal and the functions related to stopping a build have been kept since this functionality may eventually return.

components: remove stop option

---

README.md
cockpit-composer.spec.in

As of F32, the osbuild composer package no longer has the
golang-github prefix in its name. Both the new and old package
names have worked interchangibly since v3 (using Provides) and
will continue to do so until F34, but let's drop this wart sooner
rather than later.
Signed-off-by: Tom Gundersen <teg@jklm.no>

Rename the osbulid-composer dependency

---

components/ListView/ListItemImages.js
components/Modal/CreateImageUpload.js
core/actions/composes.js
core/composer.js
core/sagas/composes.js
public/custom.css
test/verify/check-image

A user may want to manually specify an image size. They may now enter a size into an input field. The size defaults to 2 GB which is also the minimum size allowed. If the size is over 2000 GB an alert is shown explaining that this image may not work on all systems.
This PR is dependent on #868, #767, and https://github.com/osbuild/osbuild-composer/pull/184

Set image size

---

test/verify/check-image

Because tar does not support image size setting, use openstack instead

test: Change image build type to openstack from tar

---

components/Modal/CreateImageUpload.js

In the CreateImageUpload wizard a user can specify an image size. The image size was missing from the action dispatcher. The image size is now included when calling the start compose action/saga.

Fix missing image size in action/saga call

---

components/Modal/CreateImageUpload.js
test/verify/check-image

Aria labels are now of the format "[field label] help". They are also now translated.

modal: improve aws help text aria labels

---

core/composer.js

These are a bit different than our other image types, but this is the
closest fit I could find without majorly reworking the API/UI.
The image types are not yet part of osbuild-composer, but I think we can
merge this eagerly as they will be ignored in case the backend doesn't
support them.
Two new image types are introduced "Fedora IoT" and "RHEL for Edge",
these are going to be very similar, but obviously available for
Fedora/RHEL respectively.
Signed-off-by: Tom Gundersen <teg@jklm.no>

compose: add ostree commit image types

---

components/ListView/ListItemImages.js
public/custom.css

The kebab menu in the Images screen, is overlaid by the log
output, whenever it is displayed.
This can be fixed by removing the sticky position from the list row.
Since the cc-m-sticky isn't used anywhere else ... I've removed it.
Fixes #975

components: Display kebab menu over logs on Images page

---

components/ListView/ListItemImages.js

Modifies how the toggle is generated so that it is included and hidden
for images without uploads, to preserve alignment in the list.
fixes #928

Fix images list view layout

---

Makefile

Cockpit's CI moved from an old Firefox 69 to the current version and
nightly builds. This requires some additional user preferences which are
fixed in cockpit master, but not in a release yet.
So check out the corresponding SHA from cockpit's test/common. Once
Cockpit 221 gets released, it can go back to cloning the tag.

test: Fix preferences for new Firefox

---

components/ListView/ListItemImages.js

This is a short term fix for #974.

Hide Logs button until logs are available

---

components/Modal/CreateImageUpload.js
pages/blueprintEdit/index.js

Includes messaging to communicate that empty blueprints result in minimal images, and packages needed for selected image types are automatically included.
fixes #973
Added the second statement in the empty state message below:
Changed the `warning` to an `info` for the Alert, and included an additional description about the minimal image.

Add messaging about empty blueprints

---

test/verify/check-image

375ccf07c introduced a special-case for Fedora, expecting different
capitalization for an image type (`openstack` vs `OpenStack`). This was
a bug in osbuild-composer-11 which has since been fixed.
Allow both capitalizations for now, so that this test doesn't fail
against the new version of osbuild-composer. This can be removed in the
future.

test/verify/check-image: don't special-case based on OS

---

Makefile

This PR adds support for running the test VM against any `osbuild` or `osbuild-composer` PR. It relies on the RPMs being built by schutzbot and stored in a publicly available repository.
```
git clone https://github.com/osbuild/cockpit-composer.git
cd cockpit-composer
make bots
bots/image-download rhel-8-3
```
```
cp ~/Downloads/osbuild-mock.repo test/
```
```
TEST_OS=rhel-8-3 make vm
```
```
bots/vm-run rhel-8-3
```
Follow instructions in MOTD to connect. Note that you may want to use cockpit-composer in a private browser session, as it has some issues when connecting to VMs (in my experience).
Note that the cockpit-composer version in the test VM, is whatever is your
current checkout when doing `make vm`.
In order to also test non-shipped versions of osbulid/osbuild-composer, there
is a …

test: add the ability to add additional repository

---

Makefile
cockpit-composer.spec.in
components/Modal/CreateImageUpload.js
core/actions/composes.js
core/composer.js
core/sagas/composes.js
test/verify/check-image
test/vm.install

A user can create a fedora-iot-commit or a rhel-edge-commit through the CreateImageUpload Wizard. If a user selects either of these image types they are required to enter an ostree parent and ref.
@jgiardino I disable the create button if the user does not enter the required Parent and Branch fields but I do not display an explicit error. Do you think I should use an alert on the input box like we do for an invalid image size?

Modals: add ability to create ostree image

---

test/vm.install

It is different in recent Fedora 31/32 images.

test: Stop hardcoding the VG name

---

pages/blueprintEdit/index.js

The input list allows users to add and remove components from a blueprint. These actions can not occur if the blueprint is still being fetched. By disabling the input list until the blueprint is loaded the
user is prevented from interacting with the list when it may reflect inaccurate data. 
This will hopefully fix #1005. This test fails when adding a component to the blueprint due to an issue concatenating. The handleAddComponent function concats twice with the blueprint components and blueprint packages. Conditionally rendering the input list should fix this issue.

pages: don't render input list until blueprint is loaded

---

test/verify/check-image

The ostree test was failing due to an avc and selinux denial. The test has been updated to ignore these journal messages. This is a temporary fix for #1022 until these messages are no longer printed.

test: allow selinux journal messages

---

core/actions/inputs.js
core/composer.js
core/reducers/inputs.js
core/sagas/inputs.js
pages/blueprintEdit/index.js
public/custom.css

This update displays an empty state in the Available Components panel, shown below, when a specified filter returns no results. This is the same messaging we display in the Blueprint Components panel, but additional css is included so that the empty state component fits with the current styling of the side panel.

Add empty state when filter returns no available components

---

.github/workflows/coverity.yml
Makefile

This is based off the coverity setup used in https://github.com/osbuild/osbuild/pull/453. Coverity can be downloaded, the build run, and the results archived and submitted to coverity for analysis. The environment variables COVERITY_EMAIL and COVERITY_TOKEN need to be defined to run coverity from the Makefile. Also, coverity has a build limit so the github action will only run once per day.

Add coverity scan github action

---

test/verify/check-image
test/vm.install

With the added support for both fedora-iot-commits and rhel-edge-commits the ostree test now runs on both fedora-32 and rhel-8.
This test won't pass until osbuild-composer v15 is available.

test: add rhel ostree test

---

pages/blueprint/index.js

Checking if users is undefined is useless since users cannot be undefined since it is set locally. This was causing a coverity error
because we accessed users before the undefined check. This check is now removed.

pages: remove undefined check on users

---

components/ListView/ComponentDetailsView.js
pages/blueprintEdit/index.js

There is an implicit_this coverity issue #1009 with the call to handleUpdateComponent from the ComponentDetailsView. The function call has been refactored to follow the same pattern as the call to handleAddComponent which does not have a coverity issue.

components: refactor handleUpdateComponent

---

components/Wizard/CreateImageUpload.js
components/Wizard/ReviewStep.js

In the review step the image type displays  as the image type's label. It was displaying as the image type's name which is less descriptive than the label.
This depends on #1035
This fixes #960

Fix wizard's review step type field

---

cockpit-composer.spec.in

The "Suggests" hint does not always resolve our dependencies as desired so, for new releases, cockpit-composer specifically requires osbuild-composer. For distros that cockpit-composer has already released into, the "weldr" group remains the requirement so that users already running osbuild-composer as the backend can continue to use it instead of lorax-composer. But, if osbuild-composer is unavailable, lorax is installed instead.
This fixes #1040

spec: change weldr requirement

---

components/Wizard/ReviewStep.js
test/verify/check-image

The check-image's testBasic is split into tests for the image step and the aws steps. The wizard should have tests to validate the contents of each of the pages within the CreateImageUpload wizard. The next tests added will be one for azure and one for the image type independent fields on the review page.

test: split up check-image testBasic tests

---

core/sagas/inputs.js

The API currently supports the following use cases in the string it accepts:
- User specifies multiple comma-separated values
- User specifies a wildcard
Currently, the UI takes whatever the user input is and wraps it with a wildcard. This results in a couple of issues in the case where the user intends to use a wildcard (e.g. "httpd*" for only packages starting with "httpd") or where the user wants to specify multiple filter values (as noted in #1026). 
This PR addresses both use cases:
- If multiple filter values are provided separated by comma and/or space, then these separators (i.e. " " or ", ") are converted to commas (i.e. ",").
- If the filter value includes at least one wildcard, then the filter value provided to the api uses the wildcards as entered, otherwise, the filter value …

enable filtering with multiple values or wildcards

---

components/Toolbar/BlueprintToolbar.js
pages/blueprint/index.js
pages/blueprintEdit/index.js

On the blueprint page we do not want to show the undo redo buttons. There is now a flag passed to the toolbar telling to let it know if it should display these buttons.
Fixes #1050

components: add display flag for undo redo in BlueprintToolbar

---

pages/blueprintEdit/index.js

This is another attempt at addressing the coverity failure by changing all instances of `component` that are not based on the argument passed in the function to something else.
The coverity issue flags the following in ComponentDetailsView.js:
`onClick={(e) => handleUpdateComponent(e, component, component.builds[selectedBuildIndex].version)}`
And describes the issue as `EXPLICIT_THIS_EXPECTED` along with other details.
A google search for `EXPLICIT_THIS_EXPECTED` returns a [PDF](https://www.synopsys.com/content/dam/synopsys/sig-assets/datasheets/coverity-cwe-coverage.pdf) with the following additional description of the issue: `Function Call with Incorrectly Specified Arguments`. A google search for this description provides additional …

Updates function failing coverity scan

---

lib/patternfly/_fonts.scss

Rewritting prior message:
Font weights are now fetched from https://github.com/RedHatOfficial/RedHatFont/blob/master/webfonts/red-hat-font.css
Information on the Red Hat fonts is available in multiple locations such as google fonts. We now only follow the font weights and weighted names listed in the official repository.
This PR requires changes to cockpit first since we fetch our fonts from cockpit. This will remain a draft until then.

lib/patternfly: fix red hat font weights

---

components/Wizard/ImageStep.js

The default ref for a rhel edge image is rhel/8/$ARCH/edge. The ref field now states this.
Fixes #1065

wizard: add help text to rhel edge ref

---

test/vm.install

In order to work both against RHEL8.3 Beta, and RHEL8.3 GA,
osbuild-composer had to split the repo files for the two cases. This was
done in commit
https://github.com/osbuild/osbuild-composer/commit/cc677dea3cabcf44c5debd87c5dbd99f2a3ad8c3
which will have to be back-ported to RHEL8.3. Make sure the
cockpit-composer tests continue to work when that's been done.
Signed-off-by: Tom Gundersen <teg@jklm.no>

test: add rhel-8-beta repo as well

---

components/Wizard/CreateImageUpload.js
components/Wizard/ImageStep.js

The "Blueprint" string and the sidebar label strings were not marked for translation. Also, the "Type" string was marked for translation but using a different format than the rest of the project. These are now fixed.
The step names used in the sidebar are also used when controlling progress through the wizard. The active step name is now pulled from the activeStep's props where the defaultMessage of the translatable string is located.
All strings in the wizard are now marked for translation.
This addresses some of the issues in #1084

wizard: translate all strings

---

utils/cockpituous-release

Bodhi activation point is the [next Tuesday](https://fedorapeople.org/groups/schedule/f-33/f-33-key-tasks.html).
Please DON'T merge this if you will have release in the meantime.
I'll start preparing F33 image now so you can test it on F33 as well. Feel free to block until you know it works on F33.

cockpituous: Release to Fedora 33

---

pages/blueprintEdit/index.js

The patternfly pagination component allows us to set some of the strings manually. The items per page string is now translated. 
This fixes some of the issues in #1084

pages: translate edit blueprint page pagination

---

utils/cockpituous-release

Fedora 33 is not currently supported by osbuild-composer so cockpit-composer should not release into fedora 33 until support is
added.

utils: remove fedora 33 cockpituous release

---

core/store.js
pages/blueprints/index.js
test/verify/check-service

When a user enters the blueprints page and osbuild-composer is not running they are prompted to start the socket. This same error state displays if the user is not root but the button to start the socket is disabled and alerts the user they don't have permissions. The check-service test is updated to accept the log messages associated with trying to access the api without root privileges.

pages: fix blueprints page error state

---

Makefile
test/verify/check-blueprint
test/verify/check-custom
test/verify/check-dependence
test/verify/check-image
test/verify/check-package
test/verify/check-service
test/verify/check-source

Since Cockpit version 228 we don't have anymore that 'Reuse my password'
checkbox on the login page. But old testlib (functions like `login_and_go()`)
try to use this checkbox. Therefore we need to use newer library.
Also `authorized` was replaced by `superuser`.
See https://github.com/cockpit-project/cockpit/commit/ef97e7e9a28a

tests: Update to new testlib

---

test/vm.install

New rhel-8-3 image needs name repo replacement file to `rhel-8.json` instead of `rhel-8-beta.json`.

test: Rename rhel-8-beta.json to rhel-8.json to work with osbuild-composer

---

core/composer.js
rpmversion.sh

osbuild-composer often specifies more detailed errors in the body of the response, so also log that, and try to parse it as json.
---
the bash arithmetic commit was a requirement to get cockpit-composer to make rpms on debian, also `--nodeps` for rpmbuild was required but it wouldn't be a good idea to commit that :)

better error message

---

utils/cockpituous-release

Since we stopped releasing into fedora 33, we caused a downgrade issue between fedora 32 (cockpit composer version 24 available) and fedora 33 (version 23 available). We will now release into 33 alongside 31, 32, and rawhide.

utils: add fedora 33 to cockpituous release

---

Makefile
test/verify/check-image

This is blocked on https://github.com/cockpit-project/cockpit/pull/14680

test: Use the @noretry decorator for check-image

---

test/verify/check-image

When checking for which image type the ostree should be, fedora 33 is now supported for a fedora-iot-commit.

test: add fedora 33 ostree test

---

Makefile
test/verify/check-image

This is a PR for me to debug the firefox test failures. I cannot replicate these failures locally.

Fix firefox tests

---

test/verify/check-source

The test can't find the Add Source button on firefox. This may have to do with multiple buttons having the same text.

test: fix Test Source

---

components/ListView/ComponentInputs.js
package.json

The short id package is only used for a key value and is not needed. Instead the component name is now used for the key. The component names will always be unique so they will work as a key.

components: remove shortid

---

components/Wizard/CreateImageUpload.js
components/Wizard/ImageStep.js
public/custom.css
test/verify/check-image

The image step now primarily uses pf4 react components instead of html elements with pf4 styles applied. This includes several minor improvements.
Field validation is improved. The image size field's validation style has been improved to include success and error colors and icons. The ostree ref is now validated to make sure the format of the ref won't error during the build process.
Image type is now marked as a required field. The help icons are formatted to be in line with text. The image size field is not required for all image types so it is now only displayed after selecting image type.
All changes follow patternfly's [form style guide](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms)
Fixes #1011

wizard: refactor image step

---

pages/blueprintEdit/index.css

Updates the page size menu in the pagination control on the Edit Blueprint page to drop down instead of up, by resetting
the `top` position var to the default var (for dropping down) and resetting the `transform: translateY` value to 0.

Update page size menu to display down

---

test/verify/check-image

When checking for which image type the ostree should be, rhel 8.4 is now supported for a rhel-edge-commit.
I believe this will fix our rhel 8.4 tests. Currently an error will get thrown in a rhel 8.4 machine when trying to build an ostree image because `image_type_ostree = "rhel-edge-commit"` is not set and therefore the image type can not be found. However, I am not 100% confident this will fix the issue since the logs state the image is failing with the call:
```
-> wait: ph_is_visible("#image-type")
<- {'type': 'undefined'}
```
This would lead me to assume the tests cannot find the image-type select menu. But, the image-type selector wait occurs directly before the call for using the `image_type_ostree` variable. And, since this variable needs to be set anyway, this change is required …

test: add rhel 8.4 ostree test

---

package.json

@patternfly/react-core 4.75.2 broke our builds due to a missing style for the Splitter component. Upgrading to 4.79.2 fixes the error.

package.json: update @patternfly/react-core

---

Makefile

This unblocks some Fedora image reorganization [1] which will in turn
make image preparations faster and more robust.
[1] https://github.com/cockpit-project/bots/pull/1407

Bump test/common dependency to 233

---

test/verify/check-source

In the firefox nightlies the add source modal will drop after adding a new source. In order to continue the tests we need to reopen it. We now wait until the modal has closed before we reopen it.

test: fix TestSource modal reload issue

---

test/README.md

With the incoming support for rhel-8-4 the testing README now contains the test distros we actively test on.

test: update README

---

.github/workflows/coverity.yml
.github/workflows/npm-update.yml
.github/workflows/po-refresh.yml

GitHub's base VMs don't automatically refresh package indexes, so it can
happen that one of the package dependencies get out of date and are not
available on the mirrors any more.
Run `apt update` first to ensure that the workflow installs the latest
packages.
Ported from starter-kit commit 8771907002e2.

workflows: Fix apt installation

---

test/verify/composerlib.py

The test setup should only stop the osbuild-local-worker socket if the distro is fedora 32 or 33.

test: fix call to stop osbuild-local-worker.socket

---

test/verify/check-blueprint
test/verify/check-custom
test/verify/check-dependence
test/verify/check-image
test/verify/check-package
test/verify/check-service
test/verify/check-source

`wait_present` should be used just rarely as the meaning of this
function is "Wait until present in dom", while meaning of `wait_visible`
is "Wait until in dom and visible to user". Tests should really just
check what user sees. Using `wait_present` incorrectly can lead to
broken code (just now I was fixing accordion which would never open up,
but tests were happy as they were just checking with `wait_present`)
I haven't tried this, just `sed` it. Lets see what CI think :)

tests: Always check if elements are visible

---

test/vm.install

Some of our images, like centos-8-stream, are already built from the official
cloud images instead of virt-install with LVM. More images are going to do that
soon [1], so fix vm.install to only do the LVM grow steps if the image actually
uses LVM.
[1] https://github.com/cockpit-project/bots/pull/1518

test: Fix vm.install for non-LVM cloud images

---

test/verify/check-package

Test should check release field when filter package by release, not package name

test: Fix check package release issue

---

components/EmptyState/EmptyStateInactive.js
components/ListView/BlueprintContents.js
components/ListView/BlueprintsDataList.js
components/ListView/ComponentDetailsView.js
components/ListView/ComponentInputs.js
components/ListView/ComponentSummaryList.js
components/ListView/SourcesListItem.js
components/Modal/CreateBlueprint.js
components/Modal/DeleteBlueprint.js
components/Modal/DeleteImage.js
components/Modal/EditDescription.js
components/Modal/ExportBlueprint.js
components/Modal/ManageSources.js
components/Modal/PendingChanges.js
components/Modal/StopBuild.js
components/Modal/UserAccount.js
components/Toolbar/FilterInput.js
components/Toolbar/ToolbarLayout.js
core/store.js
pages/blueprint/index.js
pages/blueprintEdit/index.js
pages/blueprints/index.js
pages/error/index.js
test/verify/check-blueprint
test/verify/check-custom
test/verify/check-dependence
test/verify/check-image
test/verify/check-package
test/verify/check-service
test/verify/check-source

See https://www.patternfly.org/v4/ux-writing/capitalization
19% of strings were using title case.
This breaks translations, but they will be just fuzzy, so very easy to
fix up by translators. It would be possible to also change `.po` files,
but then we would need to manually fix Weblate. Also I believe that this
is not that big number of strings and gives translators chance to go
through and fix strings properly (as I've seen people translating title
case as title case).
This was done by:
```
make po/cockpit-composer.pot
msggrep --no-wrap --msgid -e '[A-Z].*\s[A-Z]' po/cockpit-composer.pot | grep "^msgid " | cut -d " " -f2- | sort --reverse > titles
<manually reviewing strings in titles and removing the ones, that don't apply>
<copying "tools/title2sentence.py" from …
```

Use sentence case rather than title case

---

test/vm.install

Some of our images, like centos-8-stream, are already built from the official
cloud images instead of virt-install with LVM. More images are going to do that
soon [1], so fix vm.install to only do the LVM grow steps if the image actually
uses LVM.
[1] https://github.com/cockpit-project/bots/pull/1518
Cherry-picked from master commit d1fa01f291

[rhel-8 backport] test: Fix vm.install for non-LVM cloud images

---

.github/workflows/coverity.yml
.github/workflows/npm-update.yml
.github/workflows/po-refresh.yml
.github/workflows/release.yml

GitHub's 18.04 additional repositories break NPM. As "ubuntu-latest" is
going to switch to 20.04 soon anyway [1], do the jump now.
[1] https://github.com/actions/virtual-environments/issues/1816
If you look into `Actions` tab, all actions were failing for some time now.

workflows: Move actions to Ubuntu 20.04

---

test/verify/check-service
test/verify/composerlib.py

We do not test against/release in any distros that do not contain osbuild-composer v25 which includes support for local workers. In order to completely disable osbuild-composer the worker socket needs to be disabled alongside the osbuild-composer service and weldr api socket. These are now disabled on all distros not just fedora 32 and 33.

test: disable worker socket on all distros

---

test/verify/check-source

Rebase one commit(test: fix TestSource modal reload issue) from master to fix [check_source issue](https://logs.cockpit-project.org/logs/pull-1527-20210114-181122-84bf7018-rhel-8-3-firefox-osbuild-cockpit-composer-rhel-8/log.html#22-2) on `rhel-8` branch.

Rhel8 rebase

---

utils/cockpituous-release

Fedora "master" branches were renamed to "rawhide" recently.

utils: Rename Fedora rawhide branch in cockpituous control file

---

components/Wizard/ImageStep.js
test/verify/check-image

Support for uploading to vmware has not yet landed in osbuild-composer. This patch temporarily removes the upload option.

Wizard: temporarily disable uploading to vmware.

---

core/sagas/composes.js

If the tar image type is available it will now have the descriptive label of Disk Archive (.tar) in the list of image types.

core: add descriptive label for tar image type

---

package.json

It's part of patternfly-react, so we should update it in a controlled
fashion. Letting it auto-update freely often breaks the build.
package.json's versions of PatternFly in this branch don't build any
more with the current react-styles version:
ERROR in ./node_modules/@patternfly/react-core/dist/esm/components/Drawer/DrawerPanelContent.js
Module not found: Error: Can't resolve '@patternfly/react-styles/css/components/Drawer/DrawerIframe'
in 'cockpit-composer/node_modules/@patternfly/react-core/dist/esm/components/Drawer'
Pin down react-styles to the version that it had for release 28.

[rhel8] package.json: Lock @patternfly/react-styles version

---

components/Wizard/ImageStep.js

Most of the image type labels are proper nouns and haven't needed to be translated. But, with the addition of a descriptive label for tar, these labels should now be translated.

wizard: translate image type labels

---

components/Wizard/ImageStep.js

In order for image type labels to be translated they cannot be passed by an object. The image type labels needing translation are now explicitly declared.
This is a subpar fix but a quick fix is needed before string freeze.

wizard: fix image type translations

---

utils/cockpituous-release

bodhi activation for Fedora 34 is today [1]. Drop Fedora 32 instead,
which is soon EOL.
[1] https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html
----
This is what I did to cockpit{,-podman,ostree}. Of course feel free to adjust if you want to keep F32 for a while. This is mostly a reminder that this needs doing.

cockpituous: Add Fedora 34, drop Fedora 32

---

package.json
public/manifest.json

This field was introduced in
https://github.com/cockpit-project/cockpit/pull/4964 as "purely
informational for now", and isn't even parsed by cockpit.
package.json's version would only be relevant for publishing NPM
modules, but cockpit pages are not that.
We never maintained these two fields in this project, so just get rid of
them.
This makes the git tag the single source of truth for the version
number.
Cherry-picked from https://github.com/cockpit-project/starter-kit/commit/4171293c4

Drop unused version numbers from package.json and manifest

---

test/run
test/verify/check-image

The OSTree build needs more memory than the standard 1.1GiB RAM
nondestructive VMs. This was leading to excessive memory pressure, CPU
churn (from constantly trying to move things around), and eventually
crashing VMs and long timeouts.
This gets aggravated on cloud images which don't have swap; fedora-33 is
being moved to a cloud image in https://github.com/cockpit-project/bots/pull/1719
Split out the test into a destructive class which provisions a bigger
machine.
Also drop the obsolete test skip on Fedora 31, we are not supporting
that any more.

test: Run OSTree test in VM with more RAM

---

Makefile

Due to PR https://github.com/cockpit-project/bots/pull/1766
Cherry-picked from master commit 941cfc911ef.

Update for new lib folder of bots project

---

components/Wizard/CreateImageUpload.js
components/Wizard/ImageStep.js
test/verify/check-image

The RHEL for Edge Container and Installer image types are now supported. The tests will fail until osbuild-composer 28.1 is in the RHEL 8.4 nightly.
The RHEL for Edge Container (.tar) image type supports the optional ostree fields for a parent commit, a ref for the name of the branch, and a url for the parent repository.
The RHEL for Edge Installer (.iso) image type supports the required ostree fields of a ref for the name of the branch and a url for the parent repository. If the url is not provided the user will not be able to create an image. If the user enters an empty value for the url they will receive an error message. This error message has been used elsewhere in the CreateImageUpload Wizard so is already translated. This string should have a period at the end but I will leave it …

Add RHEL Edge Container and Installer image types

---

package.json

postcss 7 is vulnerable Regular Expression Denial of Service and is unused by cockpit-composer.

package.json: remove postcss

---

test/verify/check-source

The repo url in check-source's testBasic was broken. This has now been replaced by a fedora 30 mirrorlist which should maintain more reliability. Additionally the packages check is removed from this test. Packages are checked in the check-package test.

test: update check-source

---

webpack.config.js

We're getting a lot of warnings like
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
from PatternFly 3.
We can disable these warnings for our dependencies with the
`quietDeps` option to Dart Sass, as we do in the cockpit repo.

webpack.config.js: silent sass deprecation warnings

---

Makefile

The cockpit-composer-weblate repo is now using 'main', as well.

Makefile: update weblate branch to 'main'

---

Makefile
components/Modal/ManageSources.js
components/Modal/UserAccount.js
test/verify/check-custom
test/verify/check-image
test/verify/check-service
test/verify/check-source
test/verify/composerlib.py

The cockpit version for testing is bumped to 248. All tests are now run with 2048 mb of nondestructive memory instead of just the image tests. Therefore, the image tests no longer need to explicitly provision more memory.

test: use 2GB nondestructive memory and fix failing tests

---

core/sagas/composes.js

If an image type was supported by osbuild-composer but not cockpit-composer it would still be displayed. Now, an image type must be listed in the list of imageTypeLabels for it to be displayed in the list of available image types.

core: don't display unsuported image types

---

test/verify/check-blueprint
test/verify/check-custom

The export modal test does not need to verify the contents of cockpit-composer and composer-cli. It is unnecessary to test against composer-cli. Also, the export test in TestCustom is removed since it is a duplicate test.

test: simplify testExport

---

Makefile
README.md
test/README.md
test/verify/check-image

Update makefile, tests, and README to test against f34. The default testing environment is now f33.

Test against fedora 33 and 34

---

components/Notifications/Notifications.js
components/Wizard/CreateImageUpload.js
core/actions/alerts.js
core/reducers/alerts.js
core/sagas/composes.js
pages/blueprintEdit/index.js

Alerts can now pass along an error. If a compose fails the error will be included in the alert. Currently, only a failed depsolve due to no subscription will display a message. All failures will display the alert but only errors mapped to a translated string will display an error message.

alerts: include error message

---

components/Modal/UserAccount.css
components/Modal/UserAccount.js
pages/blueprint/index.js
test/verify/check-custom

The UserAccount modal is now rewritten to use patternfly 4. It keeps the same basic functionality and validation as the existing modal but has removed some unneccessary store updates. Tests are also updated for the changes in the modal.

Modal: rewrite UserAccount modal

---

test/verify/check-custom

Part of the user account test was removed do to issues with the modal in firefox nightlies. The modal has been rewritten and the entire test can now be run.
Depends on #1351 and will remain a draft until the PR is merged.
Fixes #1336

User account test enable

---

components/Wizard/CreateImageUpload.js
components/Wizard/ImageStep.js
core/sagas/composes.js
test/verify/check-image

Add support for the edge-raw-image image type. The Repo URL is required and the user can add an optional branch ref. Testing is added to verify the fields display.

Wizard: add Edge Raw Image type

---

package.json

core-js-compat is used for getting a list of required core-js modules. We do not use this feature and have no use for core-js-compat.
https://www.npmjs.com/package/core-js-compat

package.json: remove core-js-compat

---

components/Wizard/CreateImageUpload.js
core/sagas/composes.js
test/verify/check-image

The image-installer image type is now available in cockpit-composer. Users can select it in the Create Image Wizard. It has no required configuration. Testing is added to verify the fields display as expected.

Wizard: support RHEL Installer image type

---

core/actions/blueprints.js
core/sagas/blueprints.js
pages/blueprint/index.css
pages/blueprint/index.js
test/verify/check-custom

A user can now enter an installation device as a blueprint customization.
This is a very simple implementation. The functionality is a little clunky and follows the existing work for the hostname.

blueprint: add installation_device customization

---

utils/cockpituous-release

Fedora 35 has released so Fedora 33 will reach end of life on the 30th of November. The cockpit CI for fedora 33 has been removed so we have no need to continue releasing into is since 33 is EOL and no longer tested.

utils: stop releasing into fedora 33

---

Makefile
test/verify/check-blueprint
test/verify/check-dependence
test/verify/check-package
test/verify/check-service

The shell DOM changed in Cockpit 258. Pick up the Browser.logout()
change which can deal with both old and new shell versions.
Version 257 changed the set_input_text() API: The input line now does
not stay focused implicitly:
https://github.com/cockpit-project/cockpit/commit/9b86016ce13
Adjust tests to explicitly disable the blurring if a subsequent
key_press() wants to amend the input line value.
---
This blocks the recent image refreshes like https://github.com/cockpit-project/bots/pull/2669

Bump cockpit test lib to fix Browser.logout() for cockpit 258

---

Makefile

The shell DOM changed in Cockpit 258. Pick up the Browser.logout()
change which can deal with both old and new shell versions.
---
This should fix the test regression in https://github.com/cockpit-project/bots/pull/2721

Bump cockpit test lib to 259

---

test/run

The TEST_OVERLAY_DIR must be manually created per:
https://github.com/cockpit-project/bots/commit/16aa791cd
Cherry-picked from main commit dafa4d356bd173895
---
Spotted in https://github.com/cockpit-project/bots/pull/2964 - This is just a backport.

[r8.5] test/run: create overlay dir, fix for latest firefox

---

.github/workflows/release.yml

This reverts commit 04030c4f73481cd5c11a03f2d82cb4323da80da3.

Revert "workflows: release tags now start with a v"

---

test/verify/check-image

These two tests have constantly failed for several months. They cause
blocked VM image refreshes, test timeouts (so that the other tests
often don't run), and block the infra.
----
This is a desperate measure, but these two tests currently don't help anyone. We know that either OSTree builds or the tests are broken, and it needs some maintainer effort to look at them.
See e.g. #1411 for a recent example.

test: Disable TestImage.testOSTree{Commit,Container}

---

Makefile
test/run
test/verify/check-image

run-tests recently got a new `--track-naughties` option [1] to explicitly
enable updating known issues on GitHub. Enable it for CI runs, and leave
it disabled for local runs and PackIt, as in these cases we don't want
to try and talk to GitHub.
[1] https://github.com/cockpit-project/cockpit/commit/7ef88e80ce613c
Cherry-picked from starter-kit commit a937b82cd2dc.

test: Bump Cockpit test API to 267, use --track-naughties option

---

components/ListView/BlueprintsDataList.js
components/Wizard/CreateImageWizard.js
components/Wizard/ImageCreator.js
components/Wizard/formComponents/BlueprintName.js
components/Wizard/formComponents/Review.js

The entire blueprint is not needed by the Wizard. Passing the whole
blueprint will also trigger DOM refreshes as the blueprint contents
change. Only depending on the blueprint name prevents this as well as
reduces the passing of unnecessary data.

Wizard: only pass blueprint name

---

components/Wizard/CreateImageWizard.js
components/Wizard/ImageCreator.js
components/Wizard/formComponents/FormGroupCustom.js
components/Wizard/formComponents/TextFieldCustom.js
components/Wizard/steps/details.js
components/Wizard/steps/imageOutputStepMapper.js
components/Wizard/steps/index.js
components/Wizard/steps/ostreeSettings.js
components/Wizard/validators/index.js
components/Wizard/validators/ostreeValidator.js
core/sagas/composes.js

This PR is a MVP. For some image types the details page will be empty but instead of changing the routing I am leaving it empty since soon other blueprint customization will be added to the wizard and the routing would need to be changed back.
Also see issue https://github.com/osbuild/cockpit-composer/issues/1465

Add ostree support

---

test/verify/composerlib.py

Just use the standard "command" mode, which works the same. After this
change we can drop that API.

test: Drop obsolete machine.execute(script=) mode

---

test/verify/check-source

The single test now passes, it had to be modified since Manage Sources
is now simply a button instead of a kebab option.

Testing: Fix check-source tests

---

components/Wizard/formComponents/Packages.js
components/Wizard/formComponents/Review.js

This commit fixes a bug where if the blueprint package list was empty,
the form state was not updated to reflect this. The form state's
"selected-packages" field is now correctly set to [] if a blueprint does
not contain any packages.
This commit also modifies the Review step's state management. The
package list is stored in the form state, which complicates state
management as changes to the form state do not cause re-renders. This is
problematic because the package list is retrieved via an asynchronous
API call and it is possible to click to the review step before the
package list has loaded. In this case, we would like for the Review step
to re-render when the package list loads, but changes to the form state
do not cause re-renders as noted previously! A `<FormSpy>` component is
used …

Wizard: Packages/Review step bugfix, zero packages case

---

components/Wizard/formComponents/Review.js

The number of dependencies is determined by depsolving the blueprint.
The array of dependencies does not include the blueprint packages, so
the number of packages should not be subtracted from the number of
dependencies.

Wizard: Fix number of dependencies shown on Review step

---

components/Wizard/formComponents/Packages.js

Resolves #1463. This commit removes support for modules.

Wizard: Remove modules support

---

components/Toolbar/BlueprintToolbar.js

The toolbar is now using PF4 components and can sort by Name, Version,
and Release. The undo/redo functionality is removed because it is no
longer supported.

Toolbar: fix component search toolbar for PF4

---

components/Wizard/steps/ostreeSettings.js
components/Wizard/steps/ostreeSettingsStepMapper.js

The edge-raw-image supports the Parent not the URL setting.
The edge-installer only supports User customizations.

wizard: fix the supported customizations for ostree image types

---

core/actions/blueprints.js

The blueprints/info route should not be called with an empty list of blueprint names. This will return an error which will cause us to load an error state instead of the No blueprints state.

core: fix blueprintsGetAll for when there are no blueprints

---

components/Wizard/steps/ostreeSettings.js
test/verify/check-wizard

The Parent commit is now Parent since it can be either a commit id or
ref. The help text is updated. The parent is required for raw-image,
installer, and simplified-installer. The parent is only available for
commit and container.

ostree: fix ostree customizations

---

Makefile

This brings compatibility with Python 3.11:
https://github.com/cockpit-project/cockpit/commit/4ac3051d86d
The CI tasks container is Fedora 37 now, which has that Python version.
----
Blocks https://github.com/cockpit-project/bots/pull/4002

Bump cockpit test lib to 278

---

src/components/Wizard/CreateImageWizard.js

The actual key for the private key is in fact `private_key`, see the API in osbuild-composer:
https://github.com/osbuild/osbuild-composer/blob/8d0f2d7e799a3449b2d7080d9a1926a0546c66f9/internal/weldr/upload.go#L93
I tested this manually, and it indeed fixes the OCI upload (currently, osbuild-composer fails because it doesn't get the private key).

CreateImageWizard: fix the key of oci's private key

---

src/components/Modal/DeleteImage.js

Fixes #1695.
This adds space after the sentence "Are you sure you want to delete the image?" in the "Delete image" prompt.

Modal: Add a space to the "Delete image" prompt

---

src/forms/steps/users.js
translations/en.json

Fixes #1706.
This adds validation to the username input. The pattern is consistent with `man` page of `useradd`. The username can begin with a lower case letter or an underscore, and can only contain lower case letters, digits, underscores, or dashes.

steps: Add validation to the username input

---

src/components/Modal/ImportBlueprint.css
src/components/Modal/ImportBlueprint.js

Fixes #1684.
This adds `ImportBlueprint.css` to increase the height of the modal with the file upload.

Modal: Increase height of the blueprint modal

---

src/forms/schemas/sshkeys.js
test/verify/check-blueprintWizard

Fixes #1709.
This changes the text field on the `SSH keys` step to text area and sets the SSH key as a required information for adding a key.

steps: Change text field to text area on the `SSH keys` step

---

Makefile
test/run

The Python bridge is the new cockpit-bridge rewritten in Python. Before Cockpit switches it's package over we want to be able to test if all projects are supported.

Makefile: allow testing with the Python bridge

---

src/components/Table/BlueprintTable.js

This fixes a bug when the blueprint table crashed after creating a new image. The date of the last creation of the image was previously based on a `job_finished` value which was undefined for images that were still building. Now it's based on a value of `job_created`.

Table: Fix crashing of the blueprint table when creating a new image

---

src/components/Wizard/BlueprintWizard.js

The sidebar is now clickable with valid fields. This requires having a maxStepIndex and a list of all step names. This is because of ddf.
Also, the form values may not be included in the onSubmit when clicking through the wizard so the formApi may need to be used to get the form state.
Fixes #1687

Wizard: enable clicking on sidebar

---

packit.yaml

This should enable users to have easier access to the latest and greatest cockpit-composer's features.

packit: build RPMs for more targets

---

public/io.weldr.cockpit-composer.metainfo.xml

Without a valid homepage `appstream-util validate` fails that the <url> tag is missing. As there is no real homepage and https://osbuild.org does not refer to Cockpit-composer I've used the Github page.
Currently Cockpit doesn't show Cockpit composer in the applications view which uses appstream information. It seems that the appstream data is not extracted? correctly. So maybe fixing this validation warning fixes it and a new build of [appstream-data](https://packages.fedoraproject.org/pkgs/appstream-data/appstream-data/) will show composer as well.

Add homepage to appstream metainfo

---

src/components/Modal/FilesystemCard.js

There's an obvious typo in the Filesystem card title, saying 'Firewall' instead of 'Filesystem'.

FilesystemCard: Fix typo (Fixes #1870)

---

Makefile

The most recent Chromium 113 does not work any more with sizzle, tests were hanging as soon as they switched to a frame. The latest cockpit testlib applied a workaround [1]. As the latest Cockpit library also moved to PatternFly 5, but that would be prohibitively expensive for cockpit-composer's main branch, switch to the (temporary) "274+chromium-sizzle" branch, which has that workaround backported.
Alternative approach of https://github.com/osbuild/cockpit-composer/pull/1884 so PR's can be landed at least.

Update shared cockpit files for Chromium 113 fix

---

src/components/Modal/ImportBlueprint.css
src/components/Modal/ImportBlueprint.js

823c4f13a8fa9e6f808d82cf6e60e67d5edd55f1 introduced min-height to all file upload previews. However, we don't want to have min-height for all of them, and especially not for those that have hideDefaultPreview="true". For these, having the "global" min-height causes 30rem of empty vertical space to appear, which breaks certain stuff. An example is the UploadOCIFile component used in Oracle Cloud uploads.
Fix this by scoping the CSS rule to just the ImportBlueprint component.

ImportBlueprint: scope file preview min-height to just this component

---

src/api.js
src/components/Modal/SourceCardModal.js
translations/en.json

[SourceCardModal: fix type values](https://github.com/osbuild/cockpit-composer/commit/a39a6518edf66a7cc742e4789c9b0e7db385a025) 
It's yum-baseurl, yum-mirrorlist and yum-metalink, see
https://github.com/osbuild/osbuild-composer/blob/95b4979d8876dc5ef5548d88633f47ead67e448f/internal/store/store.go#L640C2-L647C1
---
[SourceCardModal: switch to v1 weldr API](https://github.com/osbuild/cockpit-composer/commit/dae3063d83ca67b4f437b707dc5009a69f179c77) 
The v0 Weldr API actually doesn't support setting rhsm=true. Thus, we need to
switch to v1 in order to fix that. V1 requires IDs to be set on repos, so
I altered the modal to allow that.

Fix repo types and RHSM in sources

---

.github/workflows/release.yml

The unit-tests container was dropped in
https://github.com/cockpit-project/cockpit/commit/f16f1fc14b88c
Cherry-picked from https://github.com/cockpit-project/starter-kit/commit/6e1427493a

workflows: Switch release to cockpit/tasks container

---

cockpit-composer.spec.in
public/org.image-builder.cockpit-composer.metainfo.xml

In order to install cockpit-composer through cockpit the metainfo.xml should be copide into the cockpit/composer directory.

Makefile: add metainfo to cockpit dir (RHEL-4660)

---

.github/workflows/pr_best_practices.yml

This PR adds the `best practices` check that we have in most of our other repositories already. Since it's part of our official pull request flow recommendation I guess it makes sense: https://osbuild.org/docs/developer-guide/general/workflow#pull-requests-

ci: Add PR best practices check

---

src/components/Wizard/CreateImageWizard.js
src/constants.js
src/forms/steps/awsDest.js
src/forms/steps/imageOutput.js
src/forms/steps/imageOutputStepMapper.js
src/forms/steps/ostreeSettings.js
src/forms/steps/vmwareDest.js

Add the `edge-ami` and `edge-vsphere` image types. These image types require both their respective upload settings as well as the `ostree-settings`.

createimagewizard: new edge types (RHEL-4689)

---

packit.yaml

Make COPR rpm builds for any commits that land in main. This will allow us to test the project more easily.

packit: build RPMs in COPR for commits to `main`

---

Makefile

In particular, this pulls in
https://github.com/cockpit-project/cockpit/commit/7957a125baa to avoid test failures with cockpit ≥ 326.
---
This broke the most recent CentOS 10 refresh in https://github.com/cockpit-project/bots/pull/7030

Bump cockpit testlib to 327

---

.github/dependabot.yml

Since the project is not maintained, it doesn't make sense to keep dependabot submitting PRs about dependency updates.

ci: Drop dependabot integration
